Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2021-10, with the labels that each got.

#371 Linter configuration for go source
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  src/acceptance/api/basic_auth_test.go
  src/acceptance/app/app_curler.go
  src/acceptance/config/config.go
  src/changelog/.golangci.yaml
  src/changeloglockcleaner/sqldb/changelogdb.go
  src/changeloglockcleaner/sqldb/changelogdb_test.go
  src/changeloglockcleaner/sqldb/helper.go
  src/changeloglockcleaner/sqldb/helper_test.go
  src/changeloglockcleaner/sqldb/sqldb_suite_test.go
Labels: approved, chore

#370 Verify app scaling before and after upgrade
  .envrc
  .golangci.yaml
  src/acceptance/api/api_suite_test.go
  src/acceptance/api/api_test.go
  src/acceptance/app/app_suite_test.go
  src/acceptance/app/custom_metric_test.go
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/app/recurring_schedule_policy_test.go
  src/acceptance/app/specificdate_schedule_policy_test.go
  src/acceptance/config/config.go
  src/acceptance/helpers/apps.go
  src/acceptance/helpers/helpers.go
  src/acceptance/helpers/org_space.go
  src/acceptance/helpers/policy.go
  src/acceptance/helpers/services.go
  src/acceptance/smoke/post_upgrade/dynamic_policy_test.go
  src/acceptance/smoke/post_upgrade/post_upgrade_suite_test.go
  src/acceptance/smoke/pre_upgrade/dynamic_policy_test.go
  src/acceptance/smoke/pre_upgrade/pre_upgrade_suite_test.go
Labels: enhancement, approved

#337 Bump postgres-release to v27
  templates/app-autoscaler-deployment.yml
Labels: dependencies

#373 Remove app-curler to reduce bloat in logs
  src/acceptance/app/app_curler.go
  src/acceptance/app/curl.go
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/helpers/apps.go
Labels: approved

#382 Port back cpu scaling test from upgrade tests to App tests
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/assets/app/nodeApp/app.js
  src/acceptance/helpers/apps.go
  src/acceptance/helpers/helpers.go
  src/acceptance/post_upgrade/post_dynamic_policy_test.go
  src/acceptance/pre_upgrade/pre_dynamic_policy_test.go
Labels: approved

#387 Increase timeout to 5minutes for pre/post upgrade test
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/app/recurring_schedule_policy_test.go
  src/acceptance/post_upgrade/post_dynamic_policy_test.go
  src/acceptance/pre_upgrade/pre_dynamic_policy_test.go
Labels: approved
