Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2021-12, with the labels that each got.

#448 Vendor files for the acceptance tests;
  scripts/update
  src/acceptance/.gitignore
Labels: approved, chore

#451 Fix changelog generation when previous release cannot be found
  src/changelog/main.go
Labels: bug, approved

#453 Adding tools.go to cover ginkgo dependency
  src/acceptance/go.sum
  src/acceptance/tools.go
Labels: approved

#452 Patch for bug in golang with montery
  Makefile
Labels: approved

#450 Add a GHA to validate node vendoring
  .github/workflows/node-vendoring.yaml
  .tool-versions
  src/acceptance/assets/app/nodeApp/node_modules/.package-lock.json
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/LICENSE
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/README.md
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-00/hyper-schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-00/json-ref
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-00/links
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-00/schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-01/hyper-schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-01/json-ref
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-01/links
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-01/schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-02/hyper-schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-02/json-ref
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-02/links
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-02/schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/examples/address
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/examples/calendar
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/examples/card
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/examples/geo
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/examples/interfaces
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/hyper-schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/json-ref
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/links
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-03/schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-04/hyper-schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-04/links
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-04/schema
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-zyp-json-schema-03.xml
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/draft-zyp-json-schema-04.xml
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/lib/links.js
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/lib/validate.js
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/package.json
  src/acceptance/assets/app/nodeApp/node_modules/json-schema/test/tests.js
  src/acceptance/assets/app/nodeApp/node_modules/jsprim/CHANGES.md
  src/acceptance/assets/app/nodeApp/node_modules/jsprim/package.json
  src/acceptance/assets/app/nodeApp/package-lock.json
  src/acceptance/assets/app/nodeApp/package.json
Labels: approved

#454 Uses storedb tag correctly to assign db credentials
  jobs/golangapiserver/templates/apiserver.yml.erb
  spec/jobs/golangapiserver/apiserver_spec.rb
Labels: bug, approved

#455 Switch to the cf-test-helper fork
  .golangci.yaml
  src/acceptance/config/config.go
  src/acceptance/go.mod
  src/acceptance/go.sum
Labels: approved

#456 Bump cf-test-helper fork to 1.1.2
  src/acceptance/config/config.go
  src/acceptance/go.mod
  src/acceptance/go.sum
Labels: approved

#457 Bump log4j version due to CVE
  src/scheduler/pom.xml
Labels: dependencies

#459 CVE-2021-45046
  src/scheduler/pom.xml
Labels: dependencies, approved

#461 Log4J 2.17.0
  src/scheduler/pom.xml
Labels: dependencies, approved

#463 Correct dependabot config after java source move
  .github/dependabot.yaml
Labels: dependencies

#471 Fix java linter
  style-guide/inspect-java-format-0.1.sh
Labels: bug, approved

#469 Replace log4j with logback
  .gitignore
  src/scheduler/pom.xml
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/SchedulerApplication.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/beanPostProcessor/DatasourceBeanPostProcessor.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingRecurringScheduleStartJob.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingScheduleEndJob.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingScheduleJob.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingScheduleStartJob.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingSpecificDateScheduleStartJob.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/rest/ControllerExceptionHandler.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleRestController.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleSyncRestController.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManager.java
  src/scheduler/src/main/resources/application.properties
  src/scheduler/src/main/resources/log4j2.xml
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingScheduleJobTest.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleRestControllerCreateScheduleAndNofifyScalingEngineTest.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManagerTest.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/util/TestDataSetupHelper.java
Labels: approved, chore

#470 Skip the mtls tests by default
  src/acceptance/bin/test_default
Labels: bug, approved
