Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2021-11, with the labels that each got.

#404 Enable the dynatrace flag
  src/common/utils.sh
Labels: approved, chore

#403 Update default max and idle db connections
  jobs/eventgenerator/spec
  jobs/golangapiserver/spec
  jobs/metricsforwarder/spec
  jobs/metricsgateway/spec
  jobs/metricsserver/spec
  jobs/operator/spec
  jobs/scalingengine/spec
Labels: bug, approved

#401 url_encode credentials in PostgreSQL URLs
  jobs/eventgenerator/templates/eventgenerator.yml.erb
  jobs/golangapiserver/templates/apiserver.yml.erb
  jobs/metricsforwarder/templates/metricsforwarder.yml.erb
  jobs/metricsgateway/templates/metricsgateway.yml.erb
  jobs/metricsserver/templates/metricsserver.yml.erb
  jobs/operator/templates/operator.yml.erb
  jobs/scalingengine/templates/scalingengine.yml.erb
Labels: enhancement, go, approved

#410 Added makefile for linting
  .github/workflows/golangci-lint.yaml
  Makefile
Labels: approved

#402 Enable rotation credentials for service broker
  Gemfile.lock
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/apiserver.yml.erb
  spec/jobs/golangapiserver/apiserver_spec.rb
Labels: enhancement, approved

#405 Add quota managment configuration
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/apiserver.yml.erb
  spec/jobs/golangapiserver/apiserver_spec.rb
Labels: enhancement, approved

#406 Add plan check configuration
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/apiserver.yml.erb
  spec/jobs/golangapiserver/apiserver_spec.rb
Labels: enhancement, approved

#413 Allow the configuration of app/service prefixes & service broker
  src/acceptance/api/api_suite_test.go
  src/acceptance/app/recurring_schedule_policy_test.go
  src/acceptance/app/specificdate_schedule_policy_test.go
  src/acceptance/broker/broker_test.go
  src/acceptance/config/config.go
  src/acceptance/helpers/apps.go
  src/acceptance/helpers/helpers.go
Labels: approved

#412 Adding policy user authorization test
  src/acceptance/api/api_suite_test.go
  src/acceptance/api/api_test.go
Labels: approved, chore

#414 Enable nats tls by default
  REQUIRED_OPS_FILES
Labels: approved

#417 Remove the autoscaler-src package
  .github/workflows/gosub.yaml
  packages/autoscaler-src/packaging
  packages/autoscaler-src/spec
  packages/eventgenerator/packaging
  packages/eventgenerator/spec
  packages/golangapiserver/packaging
  packages/golangapiserver/spec
  packages/metricsforwarder/packaging
  packages/metricsforwarder/spec
  packages/metricsgateway/packaging
  packages/metricsgateway/spec
  packages/metricsserver/packaging
  packages/metricsserver/spec
  packages/operator/packaging
  packages/operator/spec
  packages/scalingengine/packaging
  packages/scalingengine/spec
  scripts/sync-package-specs
Labels: approved

#420 Update the src lists in a dependabot PR
  .github/workflows/dependabot_update.yaml
Labels: approved

#430 Fix templating for credential binding config
  jobs/golangapiserver/templates/apiserver.yml.erb
  jobs/metricsforwarder/templates/metricsforwarder.yml.erb
  spec/jobs/golangapiserver/apiserver_spec.rb
  spec/jobs/metricsforwarder/metricsforwarder_spec.rb
Labels: bug, approved

#436 Replace String Comparing with JSON
  src/acceptance/api/api_test.go
  src/acceptance/api/basic_auth_test.go
Labels: approved
