Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2021-09, with the labels that each got.

#332 An ops file to add a persistent disk for postgres
  .github/workflows/manifest.yaml
  example/manifest_tests.sh
  example/operation/postgres-persistent-disk.yml
Labels: enhancement, approved

#336 Fix changelog generation when querying submodules
  src/changelog/main.go
  src/changelog/util/git.go
  src/changelog/util/git_test.go
Labels: bug, approved

#350 Added some docs for health monitors
  README.md
Labels: approved, chore

#359 Bump java from 11.0.11_9 to 11.0.12_7
  config/blobs.yml
  packages/java/packaging
  packages/java/spec
  src/common/java-helper.sh
Labels: dependencies

#356 Switch to temurin as the java dist
  .github/workflows/bosh.yaml
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
Labels: approved

#358 Configure envrc and tool-versions for project
  .envrc
  .tool-versions
Labels: approved, exclude-from-changelog

#366 bump routing to 0.223.0, ops file to enable nats tls
  example/operation/enable-nats-tls.yml
  example/operation/loggregator-certs-from-cf.yml
  templates/app-autoscaler-deployment.yml
Labels: dependencies

#367 Ensure we are logged in before performing cleanup in acceptance
  src/acceptance/api/api_suite_test.go
  src/acceptance/app/app_suite_test.go
Labels: bug, approved
