Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2022-09, with the labels that each got.

#866 Fix issue with counting more than just web processes
  src/autoscaler/api/publicapiserver/middleware.go
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_integration_test.go
  src/autoscaler/cf/app_processes.go
  src/autoscaler/cf/app_processes_test.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/cf_suite_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/client_test.go
  src/autoscaler/cf/endpoints_test.go
  src/autoscaler/cf/oauth.go
  src/autoscaler/cf/retriever_test.go
  src/autoscaler/cf/roles_test.go
  src/autoscaler/cf/service_instances_test.go
  src/autoscaler/cf/service_plans_test.go
  src/autoscaler/cf/testdata/test_app/deploy.sh
  src/autoscaler/cf/testdata/test_app/manifest.yml
  src/autoscaler/fakes/fake_cf_client.go
  src/autoscaler/operator/applicationsyncer.go
  src/autoscaler/scalingengine/scalingengine.go
  src/autoscaler/scalingengine/scalingengine_test.go
  src/autoscaler/testhelpers/mocks_test.go
Labels: allow-acceptance-tests

#872 Update the lint configuration
  .golangci.yaml
  Makefile
  src/autoscaler/.golangci.yaml
  src/autoscaler/testhelpers/gomega_extensions.go
Labels: exclude-from-changelog

#871 Adding Idle connection pool configuration options
  Makefile
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/apiserver.yml.erb
  jobs/operator/spec
  jobs/operator/templates/operator.yml.erb
  jobs/scalingengine/spec
  jobs/scalingengine/templates/scalingengine.yml.erb
  packages/golangapiserver/spec
  packages/operator/spec
  packages/scalingengine/spec
  spec/Gemfile
  spec/Gemfile.lock
  spec/jobs/cf/cf_spec.rb
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_processes.go
  src/autoscaler/cf/app_processes_test.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/cf_suite_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/client_test.go
  src/autoscaler/cf/config.go
  src/autoscaler/cf/endpoints.go
  src/autoscaler/cf/helpers_test.go
  src/autoscaler/cf/lazy.go
  src/autoscaler/cf/lazy_test.go
  src/autoscaler/cf/oauth.go
  src/autoscaler/cf/oauth_test.go
  src/autoscaler/cf/retriever.go
  src/autoscaler/cf/retriever_test.go
  src/autoscaler/cf/roles.go
  src/autoscaler/cf/service_instances.go
  src/autoscaler/cf/service_plans.go
  src/autoscaler/cf/testdata/app.json
  src/autoscaler/cf/testdata/app_processes.json
  src/autoscaler/cf/uaa_client.go
  src/autoscaler/cf/uaa_client_test.go
  src/autoscaler/fakes/fake_cf_client.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/testhelpers/gomega_extensions.go
  src/autoscaler/testhelpers/gomega_extensions_test.go
  src/autoscaler/testhelpers/mocks.go
Labels: allow-acceptance-tests

#874 Adding sensible idle connection setting to the internal client
  src/autoscaler/helpers/httpclient.go
Labels: bug, allow-acceptance-tests

#873 Setting a minimum file handle limits to 16k
  jobs/Gemfile
  jobs/Gemfile.lock
  jobs/eventgenerator/templates/eventgenerator_ctl
  jobs/golangapiserver/templates/apiserver_ctl.erb
  jobs/metricsforwarder/templates/metricsforwarder_ctl
  jobs/metricsgateway/templates/metricsgateway_ctl
  jobs/metricsserver/templates/metricsserver_ctl
  jobs/operator/templates/operator_ctl
  jobs/scalingengine/templates/scalingengine_ctl
  jobs/scheduler/templates/scheduler.erb
  src/common/utils.sh
Labels: bug, allow-acceptance-tests

#886 Fix for issue #814: Connection leak fix in cf api client.
  src/autoscaler/cf/app_integration_test.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/drain_transport.go
  src/autoscaler/cf/drain_transport_test.go
  src/autoscaler/cf/helpers_stress_test.go
  src/autoscaler/cf/helpers_test.go
  src/autoscaler/cf/retriever.go
  src/autoscaler/cf/retriever_test.go
Labels: allow-acceptance-tests

#884 Reenable /debug/pprof if basic auth is enabled
  src/autoscaler/healthendpoint/health_readiness_test.go
  src/autoscaler/healthendpoint/server.go
Labels: allow-acceptance-tests

#861 GHA refactoring
  .github/actions/pending-check/action.yaml
  .github/actions/pending-check/pending_check.sh
  .github/actions/setup-environment/action.yaml
  .github/actions/setup-environment/install_cli.sh
  .github/actions/setup-go/action.yaml
  .github/actions/setup-java/action.yaml
  .github/docs/act.md
  .github/workflows/acceptance_tests_broker.yaml
  .github/workflows/acceptance_tests_broker_close.yaml
  .github/workflows/acceptance_tests_buildin.yaml
  .github/workflows/acceptance_tests_buildin_close.yaml
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependabot_update.yaml
  .github/workflows/generate.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/image.yaml
  .github/workflows/java-ci-lint.yaml
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
  .github/workflows/tidy-go-mod.yaml
  Makefile
  ci/autoscaler/scripts/pr-vars.source.sh
  ci/autoscaler/scripts/run-acceptance-tests.sh
Labels: chore, allow-acceptance-tests

#887 Concourse: add acceptance tests for buildin mode
  ci/autoscaler/pipeline.yml
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/set-pipeline.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#893 Fix pending_check reporting
  .github/actions/pending-check/action.yaml
  .github/actions/pending-check/pending_check.sh
  .github/workflows/acceptance_tests_broker.yaml
  .github/workflows/acceptance_tests_buildin.yaml
Labels: bug, exclude-from-changelog, allow-acceptance-tests

#895 Remove old ulimit setting which is obsoleted by #873
  jobs/golangapiserver/templates/apiserver_ctl.erb
  jobs/metricsforwarder/templates/metricsforwarder_ctl
  jobs/metricsgateway/templates/metricsgateway_ctl
  jobs/metricsserver/templates/metricsserver_ctl
Labels: bug, allow-acceptance-tests

#899 Cleanup before v3 changes
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  Makefile
  src/acceptance/Makefile
  src/acceptance/api/api_test.go
  src/acceptance/helpers/helpers.go
  src/acceptance/helpers/org_space.go
  src/acceptance/post_upgrade/post_custom_metric_test.go
  src/autoscaler/Makefile
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/cf_suite_test.go
  src/autoscaler/cf/endpoints_test.go
  src/autoscaler/cf/errors.go
  src/autoscaler/cf/errors_test.go
  src/autoscaler/cf/helpers_stress_test.go
  src/autoscaler/cf/mocks/mocks.go
  src/autoscaler/cf/mocks/mocks_suite_test.go
  src/autoscaler/cf/mocks/mocks_test.go
  src/autoscaler/cf/oauth_test.go
  src/autoscaler/cf/retriever.go
  src/autoscaler/cf/retriever_test.go
  src/autoscaler/cf/roles_test.go
  src/autoscaler/cf/service_instances_test.go
  src/autoscaler/cf/service_plans_test.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/models/errors.go
  src/autoscaler/operator/applicationsyncer.go
  src/autoscaler/operator/applicationsyncer_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/scalingengine/scalingengine.go
  src/changelog/Makefile
  src/changelog/main.go
  src/changeloglockcleaner/Makefile
  src/changeloglockcleaner/sqldb/changelogdb_test.go
Labels: exclude-from-changelog, allow-acceptance-tests

#860 Refactor broker by introducing `pivotal-cf/brokerapi`
  .gitignore
  .golangci.yaml
  packages/golangapiserver/spec
  src/acceptance/broker/broker_test.go
  src/autoscaler/api/brokerserver/broker.go
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_handler_internal_test.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/brokerserver/broker_server_test.go
  src/autoscaler/api/brokerserver/broker_test.go
  src/autoscaler/api/brokerserver/error.go
  src/autoscaler/api/brokerserver/error_test.go
  src/autoscaler/api/exampleconfig/catalog-example.json
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
  src/autoscaler/api/schedulerutil/schedulerutil.go
  src/autoscaler/api/schedulerutil/schedulerutil_test.go
  src/autoscaler/cred_helper/custom_metrics_cred_helper.go
  src/autoscaler/cred_helper/custom_metrics_cred_helper_test.go
  src/autoscaler/cred_helper/interface.go
  src/autoscaler/cred_helper/storedprocedure_cred_helper.go
  src/autoscaler/cred_helper/storedprocedure_cred_helper_test.go
  src/autoscaler/db/db.go
  src/autoscaler/db/sqldb/binding_sqldb.go
  src/autoscaler/db/sqldb/binding_sqldb_test.go
  src/autoscaler/db/sqldb/policy_sqldb.go
  src/autoscaler/db/sqldb/policy_sqldb_test.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb_test.go
  src/autoscaler/fakes/fake_binding_db.go
  src/autoscaler/fakes/fake_credentials.go
  src/autoscaler/fakes/fake_policy_db.go
  src/autoscaler/fakes/fake_storedprocedure_db.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/models/api.go
  src/autoscaler/operator/applicationsyncer.go
  src/autoscaler/routes/routes.go
  src/autoscaler/routes/routes_test.go
Labels: allow-acceptance-tests

#905 Remove old GitHub pages related cruft
  docs/_config.yml
  docs/_layouts/default.html
  docs/assets/css/style.scss
  docs/assets/js/main.js
Labels: exclude-from-changelog

#906 Deploy Prometheus for OSS
  .github/workflows/acceptance_tests_broker_close.yaml
  .github/workflows/acceptance_tests_buildin_close.yaml
  .github/workflows/acceptance_tests_reusable.yaml
  Makefile
  ci/autoscaler/pipeline.yml
  ci/infrastructure/pipeline.yml
  ci/infrastructure/scripts/combine-ops.sh
  ci/infrastructure/scripts/deploy-prometheus.sh
  ci/infrastructure/tasks/combine-ops.yml
  ci/infrastructure/tasks/deploy-prometheus.yml
  ci/operations/prometheus-nats-tls.yaml
Labels: allow-acceptance-tests

#910 Fix pending check
  .github/actions/pending-check/pending_check.sh
  .github/workflows/acceptance_tests_reusable.yaml
Labels: allow-acceptance-tests

#901 Moving acceptance tests to v3 api
  .golangci.yaml
  src/acceptance/helpers/cleanup.go
  src/acceptance/helpers/helpers.go
  src/acceptance/helpers/org_space.go
  src/acceptance/post_upgrade/post_upgrade_suite_test.go
  src/acceptance/pre_upgrade/pre_upgrade_suite_test.go
Labels: chore, allow-acceptance-tests

#913 Cleanup of root folder
  .github/workflows/java-ci-lint.yaml
  REQUIRED_OPS_FILES
  liquibase.properties
  manifest.yaml
  scripts/liquibase-4-test.sh
  src/fmt_chkstyle/format_checkstyle.go
Labels: allow-acceptance-tests

#916 Upgrade test fix
  ci/autoscaler/pipeline.yml
Labels: exclude-from-changelog

#923 Adding script to silence alerts
  Makefile
  ci/autoscaler/scripts/cleanup-autoscaler.sh
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/scripts/pr-vars.source.sh
  ci/autoscaler/scripts/run-acceptance-tests.sh
  ci/autoscaler/scripts/silence_prometheus_alert.sh
  ci/infrastructure/scripts/deploy-prometheus.sh
  scripts/cleanup_closed_prs.sh
  scripts/deploy_acceptance_app.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#927 Added bodyclose linter
  .golangci.yaml
  src/autoscaler/api/publicapiserver/public_api_server_test.go
  src/autoscaler/cf/drain_transport_test.go
  src/autoscaler/healthendpoint/health_readiness.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/metricsgateway/helpers/ws_helper.go
  src/autoscaler/operator/schedulersynchronizer.go
Labels: bug, allow-acceptance-tests

#931 Fix `/debug/pprof` handler registration
  src/autoscaler/healthendpoint/health_readiness_test.go
  src/autoscaler/healthendpoint/server.go
Labels: allow-acceptance-tests
