Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2022-08, with the labels that each got.

#754 Update readme to fix #472
  src/acceptance/README.md
Labels: allow-acceptance-tests

#786 update-sdk: only set `dependencies` label
  ci/autoscaler/tasks/update-sdk/create_pr.sh
Labels: allow-acceptance-tests

#710 Prevent eventgenerator crash when appId is not valid
  src/autoscaler/eventgenerator/client/metric_server_client.go
Labels: allow-acceptance-tests

#776 Adding retryclient to cf client
  packages/golangapiserver/spec
  packages/operator/spec
  packages/scalingengine/spec
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/cf_suite_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/client_test.go
  src/autoscaler/cf/config.go
  src/autoscaler/cf/config_test.go
  src/autoscaler/cf/logger_adapter.go
  src/autoscaler/cf/logger_adapter_test.go
  src/autoscaler/cf/oauth.go
  src/autoscaler/cf/oauth_test.go
  src/autoscaler/cf/service_instances.go
  src/autoscaler/cf/uaa_client.go
  src/autoscaler/cf/uaa_client_test.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/integration/components_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/operator/config/config.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_test.go
  src/autoscaler/scalingengine/config/config.go
  src/autoscaler/testhelpers/gomega_extensions.go
  src/autoscaler/testhelpers/gomega_extensions_test.go
  src/autoscaler/testhelpers/mocks.go
Labels: enhancement, allow-acceptance-tests

#501 Update to jammy stemcell
  ci/autoscaler/pipeline.yml
  templates/app-autoscaler-deployment.yml
Labels: dependencies

#782 Adding missing pagination to GET /v3/app/{guid}/processes
  scripts/cleanup_closed_prs.sh
  scripts/deploy_acceptance_app.sh
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_integration_test.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/config.go
  src/autoscaler/cf/testdata/app_processes.json
  src/autoscaler/cf/testdata/test_app/.gitignore
  src/autoscaler/cf/testdata/test_app/app.js
  src/autoscaler/cf/testdata/test_app/deploy.sh
  src/autoscaler/cf/testdata/test_app/manifest.yml
  src/autoscaler/cf/testdata/test_app/package-lock.json
  src/autoscaler/cf/testdata/test_app/package.json
Labels: allow-acceptance-tests

#779 Bump PostgreSQL release to version 35
  templates/app-autoscaler-deployment.yml
Labels: dependencies

#791 Moving from put `/v2/apps/{guid}` to the post `/v3/apps/{guid}/processes/web/actions/scale` api
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/testdata/scale_response.yml
  src/autoscaler/fakes/fake_cf_client.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/models/errors.go
  src/autoscaler/models/errors_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/scalingengine/scalingengine.go
  src/autoscaler/scalingengine/scalingengine_test.go
  src/autoscaler/testhelpers/mocks.go
Labels: allow-acceptance-tests

#799 Improve pid_guard() logic
  src/common/utils.sh
Labels: allow-acceptance-tests

#756 New default manifest for autoscaler deployments
  .github/workflows/acceptance_tests.yaml
  .github/workflows/manifest.yaml
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/scripts/register-broker.sh
  example/manifest_tests.sh
  operations/add-extra-plan.yml
  operations/add-releases.yml
  operations/cf-mysql-db.yml
  operations/disable-basicauth-on-health-endpoints.yml
  operations/enable-log-cache.yml
  operations/enable-name-based-deployments.yml
  operations/enable-nats-tls.yml
  operations/external-db.yml
  operations/instance-identity-cert-from-cf.yml
  operations/log-cache-syslog-server.yml
  operations/loggregator-certs-from-cf.yml
  operations/postgres-persistent-disk.yml
  operations/set-release-version.yml
  templates/app-autoscaler.yml
  templates/manifest_tests.sh
Labels: allow-acceptance-tests

#806 Bump `postgres` release to 36
  operations/add-releases.yml
  templates/app-autoscaler-deployment.yml
Labels: dependencies

#772 Removing models.AppEntity
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/fakes/fake_cf_client.go
  src/autoscaler/models/app.go
  src/autoscaler/models/app_test.go
  src/autoscaler/scalingengine/scalingengine.go
  src/autoscaler/scalingengine/scalingengine_test.go
Labels: allow-acceptance-tests

#812 Extracts postgres variables to ops file
  .github/workflows/acceptance_tests.yaml
  operations/add-postgres-variables.yml
  operations/log-cache-syslog-server.yml
  templates/app-autoscaler.yml
Labels: allow-acceptance-tests

#817 Audit on Db connetions lead to fix for returning DB errors correctly
  src/autoscaler/db/sqldb/appmetric_sqldb.go
  src/autoscaler/db/sqldb/binding_sqldb.go
  src/autoscaler/db/sqldb/instancemetrics_sqldb.go
  src/autoscaler/db/sqldb/policy_sqldb.go
  src/autoscaler/db/sqldb/scalingengine_sqldb.go
  src/autoscaler/db/sqldb/scheduler_sqldb.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb_test.go
Labels: bug, allow-acceptance-tests

#802 Consolidate /v3 calls
  src/acceptance/assets/app/nodeApp/app.js
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/oauth.go
  src/autoscaler/cf/oauth_test.go
  src/autoscaler/cf/retriever.go
  src/autoscaler/cf/retriever_test.go
  src/autoscaler/cf/roles.go
  src/autoscaler/cf/roles_test.go
  src/autoscaler/cf/testdata/roles.json
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_metricsserver_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/testhelpers/date.go
  src/autoscaler/testhelpers/mocks.go
  src/autoscaler/testhelpers/mocks_test.go
  src/autoscaler/testhelpers/testhelpers_suite_test.go
Labels: dependencies, allow-acceptance-tests

#819 Fixes not reusing tcp connections by reading all bytes from the response body #814
  Makefile
  src/autoscaler/cf/client.go
  src/autoscaler/cf/drain_transport.go
  src/autoscaler/cf/drain_transport_test.go
Labels: bug, allow-acceptance-tests

#820 Fix for connections not being reused if cf api returns a >=300 response
  src/autoscaler/cf/retriever.go
  src/autoscaler/cf/retriever_test.go
Labels: bug, allow-acceptance-tests

#823 Removing Unused cf client functions
  src/autoscaler/api/quota/quota_management_client.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/roles.go
  src/autoscaler/cf/service_instances.go
  src/autoscaler/fakes/fake_cf_client.go
Labels: exclude-from-changelog, allow-acceptance-tests

#824 migrated `/v2/service_instances/:guid` to `/v3/service_instances/:guid`
  src/autoscaler/cf/service_instances.go
  src/autoscaler/cf/service_instances_test.go
  src/autoscaler/cf/service_plans.go
  src/autoscaler/cf/testdata/service_instance.json
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/testhelpers/mocks.go
  src/autoscaler/testhelpers/mocks_test.go
Labels: chore, allow-acceptance-tests

#825 Added memoiser and refactored out Get instance calls
  Makefile
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/memoizer.go
  src/autoscaler/cf/memoizer_test.go
  src/autoscaler/cf/service_plans.go
Labels: chore, allow-acceptance-tests

#828 Fixed/Updated version check in acceptance/bin/test.sh
  src/acceptance/bin/test
Labels: bug, allow-acceptance-tests

#829 Refactoring out the getting the broker plan id and adding tests
  .github/workflows/bosh-release-checks.yaml
  Makefile
  packages/golangapiserver/spec
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/error.go
  src/autoscaler/api/brokerserver/error_test.go
  src/autoscaler/api/plancheck/plan_checker.go
  src/autoscaler/api/plancheck/plan_checker_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/service_plans.go
  src/autoscaler/cf/service_plans_test.go
  src/autoscaler/fakes/fake_cf_client.go
  src/autoscaler/fakes/fake_plan_checker.go
  src/autoscaler/fakes/fakes.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/helpers/memoizer/memoizer.go
  src/autoscaler/helpers/memoizer/memoizer_test.go
  src/autoscaler/testhelpers/mocks_test.go
Labels: chore, allow-acceptance-tests

#836 Migrating `v2/info` to `/` in v3 endpoint
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/client_test.go
  src/autoscaler/cf/endpoints.go
  src/autoscaler/cf/endpoints_test.go
  src/autoscaler/cf/lazy.go
  src/autoscaler/cf/lazy_test.go
  src/autoscaler/cf/oauth.go
  src/autoscaler/cf/retriever.go
  src/autoscaler/cf/retriever_test.go
  src/autoscaler/cf/roles.go
  src/autoscaler/cf/roles_test.go
  src/autoscaler/cf/service_instances.go
  src/autoscaler/cf/service_instances_test.go
  src/autoscaler/cf/service_plans.go
  src/autoscaler/cf/service_plans_test.go
  src/autoscaler/cf/testdata/endpoints.json
  src/autoscaler/fakes/fake_cf_client.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_metricsserver_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/testhelpers/mocks.go
  src/autoscaler/testhelpers/mocks_test.go
Labels: allow-acceptance-tests

#839 Add mocks for uaa and login
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_metricsserver_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/testhelpers/mocks.go
  src/autoscaler/testhelpers/mocks_test.go
Labels: allow-acceptance-tests

#842 Misc supportability fixes
  src/autoscaler/Makefile
  src/autoscaler/cf/client.go
Labels: allow-acceptance-tests

#846 Update SonarCloud config
  .github/actions/acceptance_tests_common/action.yaml
  .github/actions/setup_go/action.yaml
  .github/actions/setup_java/action.yaml
  .github/workflows/java-ci-lint.yaml
  src/scheduler/pom.xml
Labels: allow-acceptance-tests

#847 Remove `quota_management` support.
  .tool-versions
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/apiserver.yml.erb
  packages/golangapiserver/spec
  spec/jobs/golangapiserver/apiserver_spec.rb
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/brokerserver/broker_handler_internal_test.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/plancheck/plan_checker_test.go
  src/autoscaler/api/quota/quota_management_client.go
  src/autoscaler/api/quota/quota_management_client_test.go
  src/autoscaler/api/quota/quota_suite_test.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
Labels: allow-acceptance-tests
