Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2022-11, with the labels that each got.

#934 Fix: re-enabling acceptance test configuration option `node_memory_limit`
  .github/workflows/acceptance_tests_reusable.yaml
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
  .tool-versions
  Makefile
  README.md
  ci/autoscaler/scripts/vars.source.sh
  scripts/deploy_acceptance_app.sh
  src/acceptance/README.md
  src/acceptance/api/api_suite_test.go
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/assets/app/nodeApp/app.js
  src/acceptance/assets/app/nodeApp/app_manifest.yml
  src/acceptance/assets/app/nodeApp/cpu_load.mjs
  src/acceptance/assets/app/nodeApp/mem_load.mjs
  src/acceptance/assets/app/nodeApp/package-lock.json
  src/acceptance/assets/app/nodeApp/package.json
  src/acceptance/assets/app/nodeApp/worker.js
  src/acceptance/bin/push_test_app.sh
  src/acceptance/broker/broker_suite_test.go
  src/acceptance/cleanup.sh
  src/acceptance/helpers/apps.go
  src/acceptance/package-lock.json
  src/acceptance/tools.go
  templates/fix-releases.sh
Labels: bug, allow-acceptance-tests

#1012 Fixing GHA deprecation warnings
  .github/actions/setup-go/action.yaml
  .github/actions/setup-java/action.yaml
  .github/workflows/acceptance_tests_broker.yaml
  .github/workflows/acceptance_tests_buildin.yaml
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/bosh-templates.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/eslint.yaml
  .github/workflows/generate.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/java-ci-lint.yaml
  .github/workflows/manifest.yaml
  .github/workflows/node-vendoring.yaml
  .github/workflows/rubocop.yaml
  .github/workflows/shellcheck.yaml
  .github/workflows/tidy-go-mod.yaml
  .tool-versions
  Makefile
  ci/dockerfiles/autoscaler-tools/Dockerfile
  src/autoscaler/Makefile
  src/autoscaler/metricsgateway/helpers/ws_helper_test.go
Labels: allow-acceptance-tests

#1019 Add missing linters and merge existing linters to save on runners
  .github/workflows/eslint.yaml
  .github/workflows/linters.yaml
  .github/workflows/rubocop.yaml
  .github/workflows/shellcheck.yaml
  .tool-versions
  Makefile
Labels: exclude-from-changelog

#1031 improved deploy-autoscaler and make file for better readibility
  Makefile
  ci/autoscaler/scripts/deploy-autoscaler.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#958 Moving to cf_http/v2 and tlsconfig to remove deprecations
  packages/eventgenerator/spec
  packages/golangapiserver/spec
  packages/metricsforwarder/spec
  packages/metricsgateway/spec
  packages/metricsserver/spec
  packages/operator/spec
  packages/scalingengine/spec
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_suite_test.go
  src/autoscaler/eventgenerator/generator/evaluator_test.go
  src/autoscaler/eventgenerator/server/server.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/helpers/httpclient.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_operator_others_test.go
  src/autoscaler/integration/integration_scheduler_scalingengine_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
  src/autoscaler/metricsserver/cmd/metricsserver/metricsserver_suite_test.go
  src/autoscaler/metricsserver/collector/server.go
  src/autoscaler/metricsserver/collector/ws_server.go
  src/autoscaler/models/security.go
  src/autoscaler/operator/schedulersynchronizer_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/scalingengine/server/server.go
  src/autoscaler/testhelpers/clients.go
  src/autoscaler/testhelpers/ginkgo_extentions.go
  src/autoscaler/testhelpers/tls.go
Labels: chore, allow-acceptance-tests

#1021 Remove metricserver
  ci/autoscaler/operation_files.txt
  ci/autoscaler/pipeline.yml
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/scripts/vars.source.sh
  ci/autoscaler/set-pipeline.sh
  ci/autoscaler/tasks/update-sdk/vars.source.sh
  operations/remove-metricsgateway.yml
  src/acceptance/api/basic_auth_test.go
Labels: dependencies, allow-acceptance-tests

#1045 Fix for error in acceptance/cleanup.sh when no CONFIG env var is supplied
  src/acceptance/cleanup.sh
Labels: bug

#993 golang app POC
  src/acceptance/assets/app/go_app/Makefile
  src/acceptance/assets/app/go_app/app_manifest.yml
  src/acceptance/assets/app/go_app/deploy.sh
  src/acceptance/assets/app/go_app/internal/app/app.go
  src/acceptance/assets/app/go_app/internal/app/app_suite_test.go
  src/acceptance/assets/app/go_app/internal/app/app_test.go
  src/acceptance/assets/app/go_app/internal/app/memory.go
  src/acceptance/assets/app/go_app/internal/app/memory_test.go
  src/acceptance/assets/app/go_app/main.go
  src/acceptance/go.mod
  src/acceptance/go.sum
Labels: allow-acceptance-tests

#1051 Fix for minor issue in the `acceptance/bin/test` script go version check
  src/acceptance/bin/test
Labels: bug

#1046 Fix to remove serial variable from the example template
  ci/autoscaler/scripts/deploy-autoscaler.sh
  templates/app-autoscaler.yml
Labels: allow-acceptance-tests

#911 Implement retrieval of service instances and bindings through service broker interface
  packages/golangapiserver/spec
  src/acceptance/assets/file/policy/all.json
  src/acceptance/assets/file/policy/default_policy.json
  src/acceptance/broker/broker_test.go
  src/acceptance/helpers/helpers.go
  src/autoscaler/api/broker/broker.go
  src/autoscaler/api/broker/broker_suite_test.go
  src/autoscaler/api/broker/broker_test.go
  src/autoscaler/api/broker/testdata/policy.json
  src/autoscaler/api/brokerserver/broker_handler_internal_test.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/brokerserver/broker_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
  src/autoscaler/db/db.go
  src/autoscaler/db/sqldb/binding_sqldb.go
  src/autoscaler/db/sqldb/binding_sqldb_test.go
  src/autoscaler/db/sqldb/policy_sqldb.go
  src/autoscaler/db/sqldb/policy_sqldb_test.go
  src/autoscaler/fakes/fake_binding_db.go
  src/autoscaler/fakes/fake_policy_db.go
  src/autoscaler/metricsforwarder/server/custom_metrics_handlers.go
  src/autoscaler/models/api.go
  src/autoscaler/scalingengine/scalingengine.go
  templates/app-autoscaler.yml
Labels: allow-acceptance-tests

#1053 New concourse
  .gitignore
  .tool-versions
  ci/README.md
  ci/infrastructure/pipeline.yml
  ci/infrastructure/scripts/vars.source.sh
  ci/infrastructure/set-pipeline.sh
  ci/terragrunt/.envrc
  ci/terragrunt/.gitignore
  ci/terragrunt/.tool-versions
  ci/terragrunt/README.md
  ci/terragrunt/app-autoscaler/concourse/.terraform.lock.hcl
  ci/terragrunt/app-autoscaler/concourse/README.md
  ci/terragrunt/app-autoscaler/concourse/backend.tf
  ci/terragrunt/app-autoscaler/concourse/pipelines.tf
  ci/terragrunt/app-autoscaler/concourse/pipelines/api-tester/pipeline.yml
  ci/terragrunt/app-autoscaler/concourse/pipelines/api-tester/src/api.go
  ci/terragrunt/app-autoscaler/concourse/pipelines/api-tester/src/api_test.go
  ci/terragrunt/app-autoscaler/concourse/pipelines/api-tester/src/go.mod
  ci/terragrunt/app-autoscaler/concourse/pipelines/api-tester/src/go.sum
  ci/terragrunt/app-autoscaler/concourse/provider.tf
  ci/terragrunt/app-autoscaler/concourse/teams.tf
  ci/terragrunt/app-autoscaler/concourse/terragrunt.hcl
  ci/terragrunt/app-autoscaler/concourse/variables.tf
  ci/terragrunt/app-autoscaler/oss_gcs_buckets/.terraform.lock.hcl
  ci/terragrunt/app-autoscaler/oss_gcs_buckets/backend.tf
  ci/terragrunt/app-autoscaler/oss_gcs_buckets/gcs_buckets.tf
  ci/terragrunt/app-autoscaler/oss_gcs_buckets/gcs_iam_policy.tf
  ci/terragrunt/app-autoscaler/oss_gcs_buckets/terragrunt.hcl
  ci/terragrunt/app-autoscaler/oss_gcs_buckets/variables.tf
  ci/terragrunt/doc/internal_documentation.md
  ci/terragrunt/flake.lock
  ci/terragrunt/flake.nix
Labels: allow-acceptance-tests

#1060 correct default target for cf infrastructure set pipeline
  ci/infrastructure/set-pipeline.sh
Labels: allow-acceptance-tests

#1069 Prometheus deployment uses jammy stemcell
  ci/infrastructure/scripts/deploy-prometheus.sh
Labels: chore, allow-acceptance-tests

#996 Flake.nix
  .envrc
  flake.lock
  flake.nix
Labels: allow-acceptance-tests

#1072 fix bug in the acceptance test cleanup.sh
  Makefile
  src/acceptance/cleanup.sh
Labels: bug

#1074 Use admin user to purge instances in aftersuites
  src/acceptance/api/api_suite_test.go
  src/acceptance/api/api_test.go
  src/acceptance/api/basic_auth_test.go
  src/acceptance/app/app_suite_test.go
  src/acceptance/broker/broker_suite_test.go
  src/acceptance/helpers/cleanup.go
  src/acceptance/helpers/helpers.go
  src/acceptance/helpers/org_space.go
  src/acceptance/helpers/services.go
  src/acceptance/post_upgrade/post_upgrade_suite_test.go
  src/acceptance/pre_upgrade/pre_upgrade_suite_test.go
  src/acceptance/run_performance/run_benchmark_suite_test.go
  src/acceptance/setup_performance/setup_benchmark_suite_test.go
Labels: allow-acceptance-tests

#1076 Adapt background-colours to enable usage in dark github-themes;
  docs/images/autoscaler.svg
  docs/images/components-db-usage.svg
  docs/images/eventgenerator.svg
  docs/images/metrics_forwarder.svg
  docs/images/metrics_gateway.svg
  docs/images/metrics_server.svg
Labels: allow-acceptance-tests

#1086 Fix: 9.0.0 brought in mistake with TLS versions and cyphers not set correctly
  src/autoscaler/models/security.go
  src/autoscaler/testhelpers/clients.go
  src/autoscaler/testhelpers/tls.go
Labels: allow-acceptance-tests

#1056 Establish eventgenerator connection with logcache via UAA
  ci/autoscaler/scripts/deploy-autoscaler.sh
  jobs/eventgenerator/spec
  jobs/eventgenerator/templates/eventgenerator.yml.erb
  operations/enable-log-cache-via-uaa.yml
  spec/jobs/eventgenerator/eventgenerator_spec.rb
  src/autoscaler/eventgenerator/client/log_cache_client.go
  src/autoscaler/eventgenerator/client/metric_client_factory.go
  src/autoscaler/eventgenerator/client/metric_client_factory_test.go
  src/autoscaler/eventgenerator/config/config.go
  src/autoscaler/fakes/fake_go_log_cache_client.go
  src/autoscaler/models/uaa_creds.go
Labels: allow-acceptance-tests

#1095 Fix unbound debug variable
  ci/autoscaler/scripts/deploy-autoscaler.sh
Labels: allow-acceptance-tests

#1120 Fix installation of `yq` in tools image
  ci/dockerfiles/autoscaler-deploy/Dockerfile
  ci/dockerfiles/autoscaler-tools/Dockerfile
Labels: exclude-from-changelog

#1101 Increase acceptance test memory usage threshold to 87 MB
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/assets/app/nodeApp/app.js
  src/acceptance/assets/app/nodeApp/mem_load.mjs
Labels: allow-acceptance-tests
