Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2022-07, with the labels that each got.

#685 Fix database migration for MySQL
  src/common/databasechangelog-primarykey.yml
Labels: bug, approved, allow-acceptance-tests

#659 Log cache client
  .github/README.md
  .github/docs/act.md
  .github/test/event.json
  .github/workflows/acceptance_tests.yaml
  Makefile
  docs/developer_guide.md
  example/operation/enable-log-cache.yml
  example/operation/enable-name-based-deployments.yml
  example/operation/log-cache-syslog-server.yml
  jobs/eventgenerator/spec
  jobs/eventgenerator/templates/eventgenerator.yml.erb
  packages/eventgenerator/spec
  spec/jobs/eventgenerator/eventgenerator_spec.rb
  src/autoscaler/envelopeprocessor/envelope_processor.go
  src/autoscaler/envelopeprocessor/envelopeprocessor_test.go
  src/autoscaler/eventgenerator/aggregator/log_cache_client.go
  src/autoscaler/eventgenerator/aggregator/log_cache_client_test.go
  src/autoscaler/eventgenerator/aggregator/metric_client.go
  src/autoscaler/eventgenerator/aggregator/metric_poller.go
  src/autoscaler/eventgenerator/aggregator/metric_poller_test.go
  src/autoscaler/eventgenerator/client/client_suite_test.go
  src/autoscaler/eventgenerator/client/log_cache_client.go
  src/autoscaler/eventgenerator/client/log_cache_client_test.go
  src/autoscaler/eventgenerator/client/metric_client_factory.go
  src/autoscaler/eventgenerator/client/metric_client_factory_test.go
  src/autoscaler/eventgenerator/client/metric_server_client.go
  src/autoscaler/eventgenerator/client/metric_server_client_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/eventgenerator/config/config.go
  src/autoscaler/eventgenerator/config/config_test.go
  src/autoscaler/fakes/fake_envelope_processor.go
  src/autoscaler/fakes/fake_go_log_cache_client.go
  src/autoscaler/fakes/fake_grpc.go
  src/autoscaler/fakes/fake_log_cache_client.go
  src/autoscaler/fakes/fake_log_cache_creator.go
  src/autoscaler/fakes/fake_metric_server_creator_creator.go
  src/autoscaler/fakes/fake_tls_config.go
  src/autoscaler/fakes/fakes.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/helpers/loggregator_logger.go
  src/autoscaler/metricsforwarder/forwarder/metric_forwarder.go
  src/autoscaler/metricsserver/collector/envelope_processor.go
  src/autoscaler/metricsserver/collector/envelope_processor_test.go
  src/changelog/.gitignore
  templates/app-autoscaler-deployment.yml
Labels: approved, allow-acceptance-tests

#723 Update Log-cache related docs
  docs/autoscaler.svg
  docs/developer_guide.md
  docs/eventgenerator.svg
  docs/eventgenerator_proposal.svg
  docs/log-cache.md
Labels: allow-acceptance-tests

#722 Merge ci repo
  .github/actions/acceptance_tests_common/action.yaml
  .github/dependabot.yaml
  .github/workflows/acceptance_tests.yaml
  .github/workflows/image.yml
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
  .tool-versions
  ci/README.md
  ci/autoscaler/pipeline.yml
  ci/autoscaler/scripts/cleanup-autoscaler.sh
  ci/autoscaler/scripts/combine-ops.sh
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/scripts/deploy-previous-autoscaler.sh
  ci/autoscaler/scripts/register-broker.sh
  ci/autoscaler/scripts/release-autoscaler.sh
  ci/autoscaler/scripts/run-acceptance-tests.sh
  ci/autoscaler/scripts/run-integration-tests.sh
  ci/autoscaler/scripts/run-prerelease-script.sh
  ci/autoscaler/scripts/run-unit-tests.sh
  ci/autoscaler/scripts/update-dns-servers.sh
  ci/autoscaler/set-pipeline.sh
  ci/autoscaler/tasks/cleanup-autoscaler.yml
  ci/autoscaler/tasks/combine-ops.yml
  ci/autoscaler/tasks/deploy-autoscaler.yml
  ci/autoscaler/tasks/deploy-previous-autoscaler.yml
  ci/autoscaler/tasks/register-broker.yml
  ci/autoscaler/tasks/release-autoscaler.yml
  ci/autoscaler/tasks/run-acceptance-tests.yml
  ci/autoscaler/tasks/run-integration-tests.yml
  ci/autoscaler/tasks/run-prerelease-script.yml
  ci/autoscaler/tasks/run-unit-tests.yml
  ci/autoscaler/tasks/update-dns-servers.yml
  ci/autoscaler/tasks/update-sdk/create_pr.sh
  ci/autoscaler/tasks/update-sdk/task.yml
  ci/autoscaler/tasks/update-sdk/update_golang_package.sh
  ci/autoscaler/tasks/update-sdk/update_java_package.sh
  ci/autoscaler/tasks/update-sdk/update_package.sh
  ci/autoscaler/tasks/update-sdk/vendor_package.sh
  ci/dockerfiles/autoscaler-deploy/Dockerfile
  ci/dockerfiles/autoscaler-test/Dockerfile
  ci/operations/enable_mtls.yml
  example/operation/log-cache-syslog-server.yml
  templates/app-autoscaler-deployment.yml
Labels: approved, chore, exclude-from-changelog, allow-acceptance-tests

#734 fixed stale ci paths
  ci/autoscaler/tasks/deploy-previous-autoscaler.yml
  ci/autoscaler/tasks/release-autoscaler.yml
  ci/autoscaler/tasks/update-sdk/task.yml
Labels: chore, exclude-from-changelog, allow-acceptance-tests

#727 Log cache ci
  ci/autoscaler/pipeline.yml
Labels: exclude-from-changelog, allow-acceptance-tests

#737 Fix pipeline typo
  ci/autoscaler/pipeline.yml
Labels: allow-acceptance-tests

#701 fix JDK_HOME env var to use new openjdk-11 path
  jobs/scheduler/spec
  jobs/scheduler/templates/install_crt_keystore.erb
  jobs/scheduler/templates/install_crt_keystore.sh
  jobs/scheduler/templates/install_crt_truststore.erb
  jobs/scheduler/templates/install_crt_truststore.sh
  jobs/scheduler/templates/pre-start.erb
  packages/common/spec
  scripts/cleanup_closed_prs.sh
  src/common/init-db-truststore.sh
  src/common/install_cert.source.sh
Labels: allow-acceptance-tests

#570 Id error handling fixes and creating traceable test id's
  Makefile
  README.md
  src/autoscaler/Makefile
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/schedulerutil/schedulerutil.go
  src/autoscaler/eventgenerator/generator/evaluator.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_metricsserver_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_metricsgateway_metricserver_eventgenerator_scalingengine_test.go
  src/autoscaler/integration/integration_operator_others_test.go
  src/autoscaler/integration/integration_scheduler_scalingengine_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManager.java
Labels: approved, chore, exclude-from-changelog, allow-acceptance-tests

#739 Fixed acceptance tests with various labels' edge cases and skips
  .github/workflows/acceptance_tests.yaml
Labels: exclude-from-changelog, allow-acceptance-tests

#750 Changelog: Fix for not finding previous release sha
  src/changelog/github/github.go
  src/changelog/main.go
Labels: allow-acceptance-tests

#748 Added sha checks for the installed cli tools in the acceptance test GHA
  .github/workflows/install_cli.sh
Labels: allow-acceptance-tests

#753 [CI] Use bosh_release_version in release name
  ci/autoscaler/scripts/cleanup-autoscaler.sh
  ci/autoscaler/scripts/deploy-autoscaler.sh
Labels: allow-acceptance-tests

#491 Bump postgres to version 31
  templates/app-autoscaler-deployment.yml
Labels: dependencies, approved

#760 Using helper function to retrieve DBURL
  .github/workflows/create_check.sh
  .tool-versions
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/db/sqldb/appmetric_sqldb_test.go
  src/autoscaler/db/sqldb/binding_sqldb_test.go
  src/autoscaler/db/sqldb/instancemetrics_sqldb_test.go
  src/autoscaler/db/sqldb/lock_sqldb_test.go
  src/autoscaler/db/sqldb/policy_sqldb_test.go
  src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
  src/autoscaler/db/sqldb/scheduler_sqldb_test.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_suite_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/metricsgateway_suite_test.go
  src/autoscaler/metricsserver/cmd/metricsserver/metricsserver_suite_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/sync/dblock_test.go
  src/autoscaler/sync/sync_suite_test.go
  src/autoscaler/testhelpers/db.go
Labels: allow-acceptance-tests

#755 Moving V2 api to V3: /v2/app/{guid}/summary -> /v3/app
  .github/workflows/golangci-lint.yaml
  Makefile
  scripts/run_acceptance_test.sh
  src/autoscaler/Makefile
  src/autoscaler/cf/app.go
  src/autoscaler/cf/app_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/client_test.go
  src/autoscaler/cf/testdata/app.json
  src/autoscaler/cf/testdata/app_processes.json
  src/autoscaler/db/sqldb/scalingengine_sqldb.go
  src/autoscaler/fakes/fake_cf_client.go
  src/autoscaler/go.mod
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/models/app.go
  src/autoscaler/models/app_test.go
  src/autoscaler/models/errors.go
  src/autoscaler/models/errors_test.go
  src/autoscaler/operator/applicationsyncer.go
  src/autoscaler/operator/applicationsyncer_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/operator/operator.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/scalingengine/scalingengine.go
  src/autoscaler/scalingengine/scalingengine_test.go
  src/autoscaler/testhelpers/errors.go
  src/autoscaler/testhelpers/files.go
  src/autoscaler/testhelpers/mocks.go
Labels: enhancement, allow-acceptance-tests

#773 Wrapping errors from scalling history
  src/autoscaler/db/sqldb/scalingengine_sqldb.go
  src/autoscaler/scalingengine/scalingengine.go
Labels: allow-acceptance-tests
