Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2022-01, with the labels that each got.

#475 Upgrade liquibase 4.6.2
  jobs/eventgenerator/spec
  jobs/eventgenerator/templates/liquibase.properties
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/liquibase.properties
  jobs/metricsserver/spec
  jobs/metricsserver/templates/liquibase.properties
  jobs/operator/spec
  jobs/operator/templates/liquibase.properties
  jobs/scalingengine/spec
  jobs/scalingengine/templates/liquibase.properties
  jobs/scheduler/spec
  jobs/scheduler/templates/liquibase.properties
  liquibase-4-test.sh
  liquibase.properties
  src/db/pom.xml
Labels: approved, breaking-changes

#254 Update manifest template to bionic
  templates/app-autoscaler-deployment.yml
Labels: approved, breaking-changes

#477 Use the versions plugin to set liquibase version
  .gitignore
  liquibase-4-test.sh
Labels: approved, chore

#480 Bump postgres to 9.6.8(v29)
  templates/app-autoscaler-deployment.yml
Labels: dependencies, approved, breaking-changes

#476 Cleanup of API tests and fix for boarderline mem limits
  src/acceptance/api/api_test.go
Labels: approved

#483 Make golang easier to upgrade
  .github/workflows/bosh.yaml
  packages/golang/packaging
  packages/golang/spec
Labels: approved, chore

#484 Bump golang to 1.17.5
  .github/workflows/dependabot_update.yaml
  .github/workflows/generate.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/gosub.yaml
  .github/workflows/java-ci-lint.yaml
  .github/workflows/mysql.yaml
  .github/workflows/postgres.yaml
  config/blobs.yml
Labels: dependencies

#486 Make java easier to upgrade
  packages/java/packaging
  packages/java/spec
Labels: approved, chore

#485 Update go modules to 1.17
  .gitignore
  .tool-versions
  src/acceptance/go.mod
  src/acceptance/go.sum
  src/apitester/api.go
  src/apitester/api_test.go
  src/apitester/go.mod
  src/apitester/go.sum
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/changelog/go.mod
  src/changeloglockcleaner/go.mod
  src/changeloglockcleaner/go.sum
Labels: dependencies

#487 Bump java to 11.0.13 8
  config/blobs.yml
Labels: dependencies

#490 Add support for v8 CF CLI.
  src/acceptance/helpers/helpers.go
Labels: approved, breaking-change

#492 Fixing minor bash error
  .tool-versions
  Makefile
Labels: approved, chore

#502 Fix acceptance test failures due to cf8 update
  src/acceptance/broker/broker_test.go
Labels: approved, breaking-change
