Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2022-04, with the labels that each got.

#554 Schedule Dependabot update more often
  .github/dependabot.yaml
Labels: approved

#555 Allow minimum number of instances to equal maximum number of instances
  src/autoscaler/api/policyvalidator/policy_validator.go
  src/autoscaler/api/policyvalidator/policy_validator_test.go
Labels: enhancement, approved

#535 Multi CPU scaling policies
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/apiserver.yml.erb
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/assets/app/nodeApp/app.js
  src/acceptance/assets/app/nodeApp/worker.js
  src/acceptance/broker/broker_test.go
  src/acceptance/config/config.go
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/policyvalidator/policy_validator.go
  src/autoscaler/api/policyvalidator/policy_validator_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
Labels: enhancement, approved

#566 Ignore extra fields in policies
  src/acceptance/api/api_test.go
  src/acceptance/helpers/helpers.go
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/policyvalidator/policy_validator.go
  src/autoscaler/api/policyvalidator/policy_validator_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
Labels: approved

#568 Remove insecure tls option
  src/autoscaler/api/brokerserver/broker_handler.go
  src/autoscaler/api/quota/quota_management_client.go
  src/autoscaler/api/quota/quota_management_client_test.go
Labels: approved

#585 Create ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: approved, exclude-from-changelog

#587 Setting up sonarcloud.io
  .github/workflows/java-ci-lint.yaml
  Makefile
  README.md
  src/scheduler/pom.xml
  src/scheduler/spotbugs-security-exclude.xml
  src/scheduler/spotbugs-security-include.xml
Labels: approved, exclude-from-changelog

#589 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
  Makefile
Labels: approved, exclude-from-changelog
