Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2022-10, with the labels that each got.

#951 Silence prometheus alerts for 8 hours using make target
  Makefile
  ci/autoscaler/scripts/silence_prometheus_alert.sh
Labels: chore, allow-acceptance-tests

#966 Fix for missing scheduler host property in the manifest for the operator vm
  templates/app-autoscaler.yml
Labels: bug, allow-acceptance-tests

#969 Add `make cf-login` target to login to CF
  Makefile
  ci/autoscaler/scripts/cf-login.sh
  ci/autoscaler/scripts/vars.source.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#970 Cleanup autoscaler
  ci/autoscaler/pipeline.yml
  ci/autoscaler/scripts/cleanup-autoscaler-deployments.sh
  ci/autoscaler/scripts/cleanup-autoscaler.sh
  ci/autoscaler/scripts/common.sh
  ci/autoscaler/scripts/run-unit-tests.sh
  ci/autoscaler/set-pipeline.sh
  ci/autoscaler/tasks/cleanup-autoscaler-deployments.yml
  src/acceptance/cleanup.sh
Labels: chore

#976 Fix incorrect parsing and conversion of `instanceindex` param
  src/autoscaler/metricsserver/collector/metric_handler.go
Labels: allow-acceptance-tests
