Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2022-05, with the labels that each got.

#621 Fix fetching of latest commit
  src/changelog/github/github.go
  src/changelog/main.go
Labels: approved

#571 Fix templates to allow enabling mTLS for public API endpoints
  .github/workflows/rubocop.yaml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Makefile
  jobs/golangapiserver/templates/apiserver.yml.erb
  spec/jobs/eventgenerator/eventgenerator_spec.rb
  spec/jobs/golangapiserver/apiserver_spec.rb
  spec/jobs/metricsforwarder/metricsforwarder_spec.rb
  spec/jobs/metricsgateway/metricsgateway_spec.rb
  spec/jobs/metricsserver/metricsserver_spec.rb
  spec/jobs/operator/operator_spec.rb
  spec/jobs/scalingengine/scalingengine_spec.rb
  spec/jobs/scheduler/scheduler_spec.rb
Labels: approved

#622 Adding cli options to changelog generation
  src/changelog/github/github.go
  src/changelog/main.go
Labels: approved

#580 Enabling golangci-lint and ginkgo version checks
  .github/workflows/golangci-lint.yaml
  .tool-versions
  Makefile
  src/autoscaler/Makefile
Labels: approved

#606 Adds log-cache documentation related to the multi-az implementation changes
  docs/developer_guide.md
  docs/eventgenerator.svg
  docs/eventgenerator_proposal.svg
  docs/log-cache.md
  docs/metrics_forwarder.svg
  src/autoscaler/eventgenerator/aggregator/metricPoller.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
Labels: approved

#626 Fixing the CheckServiceExists to use the rest api instead of relying on the commands
  Makefile
  src/acceptance/.gitignore
  src/acceptance/Makefile
  src/acceptance/api/api_suite_test.go
  src/acceptance/app/app_suite_test.go
  src/acceptance/broker/broker_suite_test.go
  src/acceptance/go.mod
  src/acceptance/helpers/cleanup.go
  src/acceptance/helpers/helpers.go
  src/acceptance/helpers/helpers_test.go
  src/acceptance/post_upgrade/post_upgrade_suite_test.go
  src/acceptance/pre_upgrade/pre_upgrade_suite_test.go
Labels: bug, approved

#638 Removing warnings in api main.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/db/sqldb/policy_sqldb.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
  src/autoscaler/metricsserver/cmd/metricsserver/main.go
  src/autoscaler/scalingengine/cmd/scalingengine/main.go
Labels: approved, chore

#620 Refactor metric server client in event generator for log-cache
  .tool-versions
  docs/eventgenerator_proposal.svg
  src/autoscaler/db/sqldb/policy_sqldb.go
  src/autoscaler/eventgenerator/aggregator/log_cache_client.go
  src/autoscaler/eventgenerator/aggregator/log_cache_client_test.go
  src/autoscaler/eventgenerator/aggregator/metricPoller.go
  src/autoscaler/eventgenerator/aggregator/metric_client.go
  src/autoscaler/eventgenerator/aggregator/metric_poller.go
  src/autoscaler/eventgenerator/aggregator/metric_poller_test.go
  src/autoscaler/eventgenerator/aggregator/metric_server_client.go
  src/autoscaler/eventgenerator/aggregator/metric_server_client_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/eventgenerator/config/config.go
  src/autoscaler/eventgenerator/config/config_test.go
Labels: dependencies, approved

#644 Fix isse with BDSA-2022-1330 and BDSA-2022-1329 by (temporarily) pinn…
  src/scheduler/pom.xml
Labels: approved

#630 Refactor out Envelope processing
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/gosub.yaml
  docs/metrics_server.svg
  packages/metricsserver/spec
  src/autoscaler/envelopeprocessor/envelope_processor.go
  src/autoscaler/envelopeprocessor/envelopeprocessor_suite_test.go
  src/autoscaler/envelopeprocessor/envelopeprocessor_test.go
  src/autoscaler/eventgenerator/aggregator/appManager.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/metricsgateway/nozzle.go
  src/autoscaler/metricsserver/collector/envelope_processor.go
  src/autoscaler/metricsserver/collector/envelope_processor_test.go
Labels: approved

#651 fix: use sonar token as cli parameters
  .github/workflows/java-ci-lint.yaml
Labels: approved, chore

#652 Health readiness
  .github/actions/setup_go/action.yaml
  Makefile
  packages/eventgenerator/spec
  packages/golangapiserver/spec
  packages/metricsgateway/spec
  packages/metricsserver/spec
  packages/operator/spec
  packages/scalingengine/spec
  src/autoscaler/Makefile
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/healthendpoint/health_readiness_test.go
  src/autoscaler/healthendpoint/server.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
  src/autoscaler/metricsserver/cmd/metricsserver/main.go
  src/autoscaler/operator/cmd/operator/main.go
  src/autoscaler/scalingengine/cmd/scalingengine/main.go
  src/changelog/go.sum
Labels: approved

#637 Part 1 - Fixing Unit tests to run in parrallel
  src/autoscaler/.gitignore
  src/autoscaler/Makefile
  src/autoscaler/db/sqldb/appmetric_sqldb_test.go
  src/autoscaler/db/sqldb/binding_sqldb_test.go
  src/autoscaler/db/sqldb/instancemetrics_sqldb_test.go
  src/autoscaler/db/sqldb/lock_sqldb_test.go
  src/autoscaler/db/sqldb/policy_sqldb_test.go
  src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
  src/autoscaler/db/sqldb/scheduler_sqldb_test.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
Labels: chore

#661 Part 3: Fixed the scaling engine tests to work in parrallel
  Makefile
  src/autoscaler/Makefile
  src/autoscaler/db/sqldb/scalingengine_sqldb.go
  src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
Labels: approved, chore, exclude-from-changelog

#653 Metricsforwarder readiness
  src/autoscaler/Makefile
  src/autoscaler/cred_helper/custom_metrics_cred_helper.go
  src/autoscaler/cred_helper/interface.go
  src/autoscaler/cred_helper/storedprocedure_cred_helper.go
  src/autoscaler/db/db.go
  src/autoscaler/db/sqldb/policy_sqldb.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb.go
  src/autoscaler/fakes/fake_credentials.go
  src/autoscaler/fakes/fake_database_status.go
  src/autoscaler/fakes/fake_policy_db.go
  src/autoscaler/fakes/fake_storedprocedure_db.go
  src/autoscaler/fakes/fakes.go
  src/autoscaler/go.mod
  src/autoscaler/healthendpoint/database_status_collector.go
  src/autoscaler/healthendpoint/health_readiness.go
  src/autoscaler/healthendpoint/health_readiness_test.go
  src/autoscaler/healthendpoint/server.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/models/health.go
  src/autoscaler/models/health_test.go
Labels: approved

#663 Adding assert check for empty org in acceptance tests
  src/acceptance/helpers/helpers.go
Labels: approved

#667 Security fix: Health endpoint not secured if just hashes supplied
  Makefile
  src/autoscaler/healthendpoint/health_readiness_test.go
  src/autoscaler/healthendpoint/server.go
Labels: bug, approved

#670 Replace `go get` and `brew install` with `go run`
  .github/workflows/shellcheck.yaml
  .tool-versions
  scripts/generate_test_certs.sh
  src/autoscaler/Makefile
  src/scheduler/scripts/generate_unit_test_certs.sh
Labels: approved, chore

#671 Addition of 30s cache on the /health/readiness endpoint
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/config/config.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/eventgenerator/config/config.go
  src/autoscaler/healthendpoint/health_readiness.go
  src/autoscaler/healthendpoint/health_readiness_test.go
  src/autoscaler/healthendpoint/server.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
  src/autoscaler/metricsgateway/config/config.go
  src/autoscaler/metricsserver/cmd/metricsserver/main.go
  src/autoscaler/metricsserver/config/config.go
  src/autoscaler/models/health.go
  src/autoscaler/models/health_test.go
  src/autoscaler/operator/cmd/operator/main.go
  src/autoscaler/operator/config/config.go
  src/autoscaler/scalingengine/cmd/scalingengine/main.go
  src/autoscaler/scalingengine/config/config.go
Labels: enhancement, approved

#664 Part 4 more sqldb test fixes
  src/autoscaler/Makefile
  src/autoscaler/db/sqldb/appmetric_sqldb.go
  src/autoscaler/db/sqldb/appmetric_sqldb_test.go
  src/autoscaler/db/sqldb/instancemetrics_sqldb_test.go
  src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
  src/autoscaler/db/sqldb/scheduler_sqldb_test.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
Labels: approved
