Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2023-08, with the labels that each got.

#2012 Set `key_length` and `duration` on all certs
  templates/app-autoscaler.yml
Labels: allow-acceptance-tests

#995 Fix: returning 404 error if app guid does not exist
  .gitignore
  .vscode/extensions.json
  Makefile
  go.work
  src/acceptance/Makefile
  src/acceptance/assets/app/go_app/Makefile
  src/autoscaler/Makefile
  src/autoscaler/api/publicapiserver/middleware.go
  src/autoscaler/api/publicapiserver/middleware_test.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
  src/autoscaler/cf/errors.go
  src/autoscaler/cf/errors_test.go
  src/autoscaler/cf/mocks/mocks.go
  src/autoscaler/cf/mocks/mocks_test.go
  src/autoscaler/cf/oauth.go
  src/autoscaler/cf/oauth_test.go
  src/changelog/Makefile
  src/changeloglockcleaner/Makefile
Labels: allow-acceptance-tests

#2053 Add swagger update flake
  ci/dockerfiles/autoscaler-tools/Dockerfile
  flake.lock
Labels: allow-acceptance-tests

#2057 Swagger-Tool for Docker tests
  ci/dockerfiles/autoscaler-tools/Dockerfile
Labels: allow-acceptance-tests

#1755 Add OpenAPI specification for the public API
  .github/workflows/openapi-specs-check.yaml
  .gitignore
  Makefile
  api/application-metric-api.openapi.yaml
  api/custom-metrics-api.openapi.yaml
  api/policy-api.openapi.yaml
  api/scaling-history-api.openapi.yaml
  api/shared_definitions.yaml
  ci/dockerfiles/autoscaler-deploy/Dockerfile
  docs/Public_API.rst
  docs/policy.md
  flake.lock
  flake.nix
  src/acceptance/assets/app/go_app/Makefile
  src/acceptance/assets/app/go_app/internal/app/custom_metrics.go
  src/acceptance/assets/app/go_app/internal/custommetrics/api_credentials.go
  src/acceptance/assets/app/go_app/internal/custommetrics/oas_cfg_gen.go
  src/acceptance/assets/app/go_app/internal/custommetrics/oas_client_gen.go
  src/acceptance/assets/app/go_app/internal/custommetrics/oas_json_gen.go
  src/acceptance/assets/app/go_app/internal/custommetrics/oas_parameters_gen.go
  src/acceptance/assets/app/go_app/internal/custommetrics/oas_request_encoders_gen.go
  src/acceptance/assets/app/go_app/internal/custommetrics/oas_response_decoders_gen.go
  src/acceptance/assets/app/go_app/internal/custommetrics/oas_schemas_gen.go
  src/acceptance/assets/app/go_app/internal/custommetrics/oas_validators_gen.go
  src/acceptance/assets/app/go_app/internal/generate.go
Labels: enhancement, allow-acceptance-tests

#2072 Trim down `tools.go` usage
  .github/workflows/generate.yaml
  .github/workflows/golangci-lint.yaml
  .golangci.yaml
  .vscode/extensions.json
  Makefile
  ci/autoscaler/scripts/run-integration-tests.sh
  ci/autoscaler/scripts/run-unit-tests.sh
  scripts/generate_test_certs.sh
  src/acceptance/Makefile
  src/acceptance/assets/app/go_app/.gitignore
  src/acceptance/assets/app/go_app/Makefile
  src/acceptance/assets/app/go_app/internal/app/app_test.go
  src/acceptance/assets/app/go_app/internal/app/appfakes/fake_cpuwaster.go
  src/acceptance/assets/app/go_app/internal/app/appfakes/fake_custom_metric_client.go
  src/acceptance/assets/app/go_app/internal/app/appfakes/fake_memory_gobbler.go
  src/acceptance/assets/app/go_app/internal/app/appfakes/fake_time_waster.go
  src/acceptance/assets/app/go_app/internal/app/cpu.go
  src/acceptance/assets/app/go_app/internal/app/custom_metrics.go
  src/acceptance/assets/app/go_app/internal/app/memory.go
  src/acceptance/assets/app/go_app/internal/app/memory_test.go
  src/acceptance/assets/app/go_app/internal/app/responsetime.go
  src/acceptance/assets/app/go_app/internal/app/responsetime_test.go
  src/acceptance/assets/app/go_app/internal/custommetrics/basic_auth_transport.go
  src/acceptance/assets/app/go_app/tools/tools.go
  src/acceptance/tools.go
  src/autoscaler/Makefile
  src/autoscaler/fakes/.gitignore
  src/autoscaler/fakes/fake_app_metric_db.go
  src/autoscaler/fakes/fake_binding_db.go
  src/autoscaler/fakes/fake_cf_client.go
  src/autoscaler/fakes/fake_credentials.go
  src/autoscaler/fakes/fake_database_status.go
  src/autoscaler/fakes/fake_emitter.go
  src/autoscaler/fakes/fake_envelope_processor.go
  src/autoscaler/fakes/fake_envelope_processor_creator.go
  src/autoscaler/fakes/fake_go_log_cache_client.go
  src/autoscaler/fakes/fake_grpc.go
  src/autoscaler/fakes/fake_httpstatus_collector.go
  src/autoscaler/fakes/fake_instancemetrics_db.go
  src/autoscaler/fakes/fake_log_cache_client.go
  src/autoscaler/fakes/fake_log_cache_creator.go
  src/autoscaler/fakes/fake_metric_forwarder.go
  src/autoscaler/fakes/fake_metric_server_creator_creator.go
  src/autoscaler/fakes/fake_operator.go
  src/autoscaler/fakes/fake_plan_checker.go
  src/autoscaler/fakes/fake_policy_db.go
  src/autoscaler/fakes/fake_ratelimiter.go
  src/autoscaler/fakes/fake_scalingengine.go
  src/autoscaler/fakes/fake_scalingengine_db.go
  src/autoscaler/fakes/fake_scheduler_db.go
  src/autoscaler/fakes/fake_storedprocedure_db.go
  src/autoscaler/fakes/fake_sychronizer.go
  src/autoscaler/fakes/fake_wshelper.go
  src/autoscaler/fakes/fakes.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/tools.go
  src/changelog/Makefile
  src/changeloglockcleaner/Makefile
  src/changeloglockcleaner/tools.go
Labels: chore, allow-acceptance-tests

#2074 Scheduler use health endpoint monit
  jobs/scheduler/monit
  jobs/scheduler/spec
  spec/fixtures/monit
  spec/jobs/scheduler/scheduler_spec.rb
Labels: allow-acceptance-tests

#2079 Revert "Scheduler use health endpoint monit"
  jobs/scheduler/monit
  jobs/scheduler/spec
  spec/fixtures/monit
  spec/jobs/scheduler/scheduler_spec.rb
Labels: allow-acceptance-tests

#2080 APPAUTOSCALER-572 Fixing API Files
  api/application-metric-api.openapi.yaml
  api/policy-api.openapi.yaml
  api/scaling-history-api.openapi.yaml
Labels: allow-acceptance-tests
