Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2023-01, with the labels that each got.

#1259 Switch from lager fork to upstream
  src/autoscaler/Makefile
  src/autoscaler/go.mod
  src/autoscaler/go.sum
Labels: allow-acceptance-tests

#1269 Use MySQL new mvn Coordinates starting from v8.0.31
  src/scheduler/pom.xml
Labels: dependencies

#1157 Runs performance tests on existing org and space
  Makefile
  ci/autoscaler/pipeline.yml
  ci/autoscaler/scripts/cleanup-autoscaler.sh
  ci/autoscaler/scripts/run-acceptance-tests.sh
  src/acceptance/api/api_suite_test.go
  src/acceptance/api/api_test.go
  src/acceptance/app/custom_metric_test.go
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/app/recurring_schedule_policy_test.go
  src/acceptance/app/specificdate_schedule_policy_test.go
  src/acceptance/broker/broker_test.go
  src/acceptance/config/config.go
  src/acceptance/helpers/apps.go
  src/acceptance/helpers/cleanup.go
  src/acceptance/helpers/common.go
  src/acceptance/helpers/helpers.go
  src/acceptance/helpers/org.go
  src/acceptance/helpers/org_quota.go
  src/acceptance/helpers/org_space.go
  src/acceptance/helpers/retry.go
  src/acceptance/helpers/services.go
  src/acceptance/helpers/spaces.go
  src/acceptance/post_upgrade/common_test.go
  src/acceptance/post_upgrade/post_custom_metric_test.go
  src/acceptance/pre_upgrade/pre_custom_metric_test.go
  src/acceptance/pre_upgrade/pre_dynamic_policy_test.go
  src/acceptance/pre_upgrade/pre_upgrade_suite_test.go
  src/acceptance/run_performance/run_performance_suite_test.go
  src/acceptance/run_performance/run_performance_test.go
  src/acceptance/run_performance/scale_and_benchmark_test.go
  src/acceptance/setup_performance/deploy_and_bind_test.go
  src/acceptance/setup_performance/setup_benchmark_suite_test.go
  src/acceptance/setup_performance/setup_performance_suite_test.go
  src/acceptance/setup_performance/setup_performance_test.go
  src/autoscaler/metricsforwarder/server/auth/authenticator.go
Labels: allow-acceptance-tests

#1268 Update versions of software in the flake;
  .envrc
  flake.lock
Labels: allow-acceptance-tests

#1276 Remove unneeded sourcing of .envrc
  .envrc
  .github/workflows/generate.yaml
Labels: allow-acceptance-tests

#1277 Add maintenance-job to the “all”-group
  .github/workflows/golangci-lint.yaml
  ci/autoscaler/pipeline.yml
Labels: allow-acceptance-tests

#1284 Bump `postgres-release` to `44`
  operations/add-releases.yml
  templates/app-autoscaler-deployment.yml
Labels: dependencies

#1291 Improve performance test and make it run for larger app count
  Makefile
  ci/autoscaler/scripts/vars.source.sh
  src/acceptance/helpers/org.go
  src/acceptance/helpers/spaces.go
  src/acceptance/run_performance/run_performance_test.go
  src/acceptance/setup_performance/setup_performance_suite_test.go
  src/acceptance/setup_performance/setup_performance_test.go
Labels: chore, allow-acceptance-tests

#1278 Get makefile to work with nix-flake
  .envrc
  flake.lock
  flake.nix
Labels: allow-acceptance-tests

#1295 Restore previous handling of long passwords
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/healthendpoint/server.go
  templates/app-autoscaler.yml
Labels: allow-acceptance-tests

#1305 Switch `cf-test-helpers` from fork to upstream
  src/acceptance/api/api_suite_test.go
  src/acceptance/api/api_test.go
  src/acceptance/app/app_suite_test.go
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/broker/broker_suite_test.go
  src/acceptance/broker/broker_test.go
  src/acceptance/go.mod
  src/acceptance/go.sum
  src/acceptance/helpers/apps.go
  src/acceptance/helpers/cleanup.go
  src/acceptance/helpers/debug.go
  src/acceptance/helpers/helpers.go
  src/acceptance/helpers/org.go
  src/acceptance/helpers/org_quota.go
  src/acceptance/helpers/services.go
  src/acceptance/helpers/spaces.go
  src/acceptance/post_upgrade/post_upgrade_suite_test.go
  src/acceptance/pre_upgrade/pre_upgrade_suite_test.go
  src/acceptance/run_performance/run_performance_suite_test.go
  src/acceptance/setup_performance/setup_performance_suite_test.go
Labels: dependencies

#1202 WIP: Github Private Workers and Workflows
  .github/actions/setup-environment/action.yaml
  .github/actions/setup-environment/install_cli.sh
  .github/actions/setup-go/action.yaml
  .github/actions/setup-java/action.yaml
  .github/workflows/acceptance_tests_broker_close.yaml
  .github/workflows/acceptance_tests_buildin_close.yaml
  .github/workflows/acceptance_tests_reusable.yaml
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/bosh-templates.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-spec-updates.yaml
  .github/workflows/dependency-updates-auto-merge.yaml
  .github/workflows/generate.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/java-ci-lint.yaml
  .github/workflows/linters.yaml
  .github/workflows/manifest.yaml
  .github/workflows/mysql.yaml
  .github/workflows/node-vendoring.yaml
  .github/workflows/postgres.yaml
  .github/workflows/tidy-go-mod.yaml
  Makefile
  ci/autoscaler/scripts/run-unit-tests.sh
  ci/autoscaler/tasks/deploy-autoscaler.yml
  ci/autoscaler/tasks/run-integration-tests.yml
  ci/autoscaler/tasks/run-unit-tests.yml
  ci/terragrunt/app-autoscaler/github-arc-team-wg-ci/.terraform.lock.hcl
  ci/terragrunt/app-autoscaler/github-arc-team-wg-ci/config.yaml
  ci/terragrunt/app-autoscaler/github-arc-team-wg-ci/terragrunt.hcl
  scripts/initialise_db.sh
  src/acceptance/gha_trigger.txt
  src/autoscaler/db/sqldb/appmetric_sqldb_test.go
  src/autoscaler/db/sqldb/binding_sqldb_test.go
  src/autoscaler/db/sqldb/instancemetrics_sqldb_test.go
  src/autoscaler/db/sqldb/lock_sqldb_test.go
  src/autoscaler/db/sqldb/policy_sqldb_test.go
  src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
  src/autoscaler/db/sqldb/scheduler_sqldb_test.go
  src/changeloglockcleaner/sqldb/changelogdb_test.go
  src/changeloglockcleaner/sqldb/helper.go
  src/scheduler/src/main/resources/application-mysql.properties
  src/scheduler/src/main/resources/application.properties
  templates/manifest_tests.sh
Labels: 🚧🛠️ WIP, allow-acceptance-tests

#1342 Revert to using GitHub-hosted runners
  .github/workflows/acceptance_tests_broker_close.yaml
  .github/workflows/acceptance_tests_buildin_close.yaml
  .github/workflows/acceptance_tests_reusable.yaml
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/bosh-templates.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-spec-updates.yaml
  .github/workflows/dependency-updates-auto-merge.yaml
  .github/workflows/generate.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/java-ci-lint.yaml
  .github/workflows/linters.yaml
  .github/workflows/manifest.yaml
  .github/workflows/mysql.yaml
  .github/workflows/node-vendoring.yaml
  .github/workflows/postgres.yaml
  .github/workflows/tidy-go-mod.yaml
  ci/terragrunt/app-autoscaler/github-arc-team-wg-ci/.terraform.lock.hcl
  ci/terragrunt/app-autoscaler/github-arc-team-wg-ci/config.yaml
  src/acceptance/gha_trigger.txt
Labels: allow-acceptance-tests
