Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2023-11, with the labels that each got.

#2299 Replace DBCP2 database connection pool implementation with HikariCP
  src/scheduler/pom.xml
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/DataSourceConfig.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/health/DbStatusCollector.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/SchedulerApplicationTest.java
Labels: chore, allow-acceptance-tests

#2190 Fix scaling history pagination handling
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/dependency-spec-updates.yaml
  .github/workflows/dependency-update.go-mod-tidy_and_make-package-specs.yaml
  .github/workflows/tidy-go-mod.yaml
  .gitignore
  Makefile
  api/scaling-history-api.openapi.yaml
  ci/autoscaler/pipeline.yml
  packages/eventgenerator/spec
  packages/golangapiserver/spec
  packages/metricsforwarder/spec
  packages/metricsgateway/spec
  packages/metricsserver/spec
  packages/operator/spec
  packages/scalingengine/spec
  src/acceptance/assets/app/go_app/go.mod
  src/acceptance/assets/app/go_app/go.sum
  src/acceptance/assets/app/go_app/internal/app/app.go
  src/acceptance/assets/app/go_app/internal/generate.go
  src/autoscaler/Makefile
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/api/publicapiserver/public_api_server_test.go
  src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
  src/autoscaler/api/publicapiserver/scaling_history_handler.go
  src/autoscaler/db/db.go
  src/autoscaler/db/sqldb/scalingengine_sqldb.go
  src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/helpers/apis/generate.go
  src/autoscaler/helpers/handlers/handlers.go
  src/autoscaler/helpers/lager.go
  src/autoscaler/integration/helpers_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/routes/routes.go
  src/autoscaler/routes/routes_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/main.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_test.go
  src/autoscaler/scalingengine/server/scaling_handler.go
  src/autoscaler/scalingengine/server/scaling_handler_test.go
  src/autoscaler/scalingengine/server/scaling_history_handler.go
  src/autoscaler/scalingengine/server/scaling_history_handler_test.go
  src/autoscaler/scalingengine/server/server.go
  src/autoscaler/scalingengine/server/server_test.go
Labels: allow-acceptance-tests

#2316 Converge manifest-attributes
  flake.lock
  flake.nix
  templates/app-autoscaler-deployment.yml
  templates/app-autoscaler.yml
Labels: allow-acceptance-tests

#1654 external-db opsfile: update for new deployment manifest
  operations/external-db.yml
Labels: allow-acceptance-tests

#2340 Fixes
  .github/workflows/dependency-update.go-mod-tidy_and_make-package-specs.yaml
  Makefile
  scripts/sync-package-specs
  src/autoscaler/Makefile
Labels: allow-acceptance-tests

#2341 Remove `scripts/update`
  .github/workflows/tidy-go-mod.yaml
  scripts/update
Labels: chore, allow-acceptance-tests

#2345 Fix `*-release` make targets
  Makefile
Labels: exclude-from-changelog, allow-acceptance-tests

#1653 acceptance tests: allow overriding of component health endpoints
  src/acceptance/api/basic_auth_test.go
  src/acceptance/config/config.go
Labels: allow-acceptance-tests

#2346 Correctly ignore scaling events on apps without a scaling policy
  src/autoscaler/scalingengine/scalingengine.go
  src/autoscaler/scalingengine/scalingengine_test.go
Labels: bug, allow-acceptance-tests

#2360 Try to fix `memoryused` acceptance test
  .editorconfig
  .vscode/extensions.json
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/helpers/debug.go
Labels: bug, allow-acceptance-tests

#2391 fix(manifest): Do not set passwords to autoconverge
  templates/app-autoscaler.yml
Labels: bug, allow-acceptance-tests

#2389 fix(scalingengine): Correctly set scaling type in history
  src/autoscaler/scalingengine/server/scaling_history_handler.go
  src/autoscaler/scalingengine/server/scaling_history_handler_test.go
Labels: bug, allow-acceptance-tests

#2390 bump cf-deployment-concourse-tasks to v15
  ci/infrastructure/pipeline.yml
Labels: chore
