Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2023-02, with the labels that each got.

#1155 Update the logging to always have the appId so its easy to follow
  scripts/asdf-plugin-install.sh
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/route_helper.go
Labels: allow-acceptance-tests

#1073 Refacor code duplication out of basic auth test
  Makefile
  src/acceptance/api/basic_auth_test.go
Labels: allow-acceptance-tests

#1362 Refactor some common funcs from application mains
  Makefile
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/cred_helper/custom_metrics_cred_helper.go
  src/autoscaler/db/sqldb/factories.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsgateway/cmd/metricsgateway/main.go
  src/autoscaler/metricsserver/cmd/metricsserver/main.go
  src/autoscaler/operator/cmd/operator/main.go
  src/autoscaler/operator/cmd/operator/operator_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/main.go
Labels: allow-acceptance-tests

#977 Fixing possible threading issues related to concurrent map read/write
  packages/metricsgateway/spec
  src/autoscaler/eventgenerator/aggregator/appManager.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/metricsgateway/appManager.go
  src/autoscaler/metricsserver/cmd/metricsserver/main.go
  src/autoscaler/metricsserver/collector/collector.go
  src/autoscaler/metricsserver/collector/collector_test.go
  src/autoscaler/metricsserver/collector/envelope_processor.go
  src/autoscaler/metricsserver/collector/envelope_processor_test.go
Labels: bug, allow-acceptance-tests

#794 Fixing mutex handling and intermittant test failures with wshelper
  src/autoscaler/fakes/fake_wshelper.go
  src/autoscaler/fakes/fakes.go
  src/autoscaler/metricsgateway/helpers/ws_helper.go
  src/autoscaler/metricsgateway/helpers/ws_helper_test.go
Labels: allow-acceptance-tests

#1199 Refactor to use models.ScalingPolicy rather than string
  packages/golangapiserver/spec
  src/autoscaler/api/broker/broker.go
  src/autoscaler/api/broker/broker_test.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/plancheck/plan_checker.go
  src/autoscaler/api/plancheck/plan_checker_test.go
  src/autoscaler/api/policyvalidator/policy_validator.go
  src/autoscaler/api/policyvalidator/policy_validator_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
  src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
  src/autoscaler/api/schedulerclient/client.go
  src/autoscaler/api/schedulerclient/client_test.go
  src/autoscaler/api/schedulerclient/schedulerutil_suite_test.go
  src/autoscaler/api/schedulerutil/schedulerutil.go
  src/autoscaler/db/db.go
  src/autoscaler/db/sqldb/policy_sqldb.go
  src/autoscaler/db/sqldb/policy_sqldb_test.go
  src/autoscaler/fakes/fake_plan_checker.go
  src/autoscaler/fakes/fake_policy_db.go
  src/autoscaler/integration/helpers_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/models/api.go
  src/autoscaler/models/policy.go
  src/autoscaler/models/policy_test.go
Labels: allow-acceptance-tests

#1188 Describe assertions in recurring schedule acceptance test
  ci/autoscaler/scripts/run-acceptance-tests.sh
  src/acceptance/app/recurring_schedule_policy_test.go
  src/acceptance/bin/test_default
  src/acceptance/helpers/helpers.go
Labels: allow-acceptance-tests

#1097 Adding retry client to the internal clients
  packages/eventgenerator/spec
  packages/metricsforwarder/spec
  packages/metricsgateway/spec
  packages/metricsserver/spec
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
  src/autoscaler/api/schedulerclient/client.go
  src/autoscaler/cf/cf_suite_test.go
  src/autoscaler/cf/client.go
  src/autoscaler/cf/config.go
  src/autoscaler/cf/config_test.go
  src/autoscaler/eventgenerator/aggregator/metric_poller_test.go
  src/autoscaler/eventgenerator/client/metric_client_factory.go
  src/autoscaler/eventgenerator/client/metric_client_factory_test.go
  src/autoscaler/eventgenerator/client/metric_server_client.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/main.go
  src/autoscaler/helpers/httpclient.go
  src/autoscaler/operator/cmd/operator/main.go
  src/autoscaler/operator/config/config.go
  src/autoscaler/scalingengine/config/config.go
Labels: allow-acceptance-tests

#1191 Logging and error returns improvements
  src/autoscaler/api/broker/broker.go
  src/autoscaler/api/broker/broker_test.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
Labels: allow-acceptance-tests

#1306 Make Autoscaler Performance Test Resilient to Scale Apps at Scale
  src/acceptance/helpers/apps.go
  src/acceptance/helpers/helpers.go
  src/acceptance/helpers/retry.go
  src/acceptance/run_performance/run_performance_suite_test.go
  src/acceptance/run_performance/run_performance_test.go
  src/acceptance/setup_performance/setup_performance_test.go
Labels: chore, allow-acceptance-tests

#1481 Do not test with PostgreSQL 9.6 anymore, but with 15
  .github/workflows/postgres.yaml
Labels: allow-acceptance-tests
