Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2023-09, with the labels that each got.

#2104 Set `DT_APPLICATIONID` environment variables
  jobs/eventgenerator/templates/bpm.yml.erb
  jobs/golangapiserver/templates/bpm.yml.erb
  jobs/metricsforwarder/templates/bpm.yml.erb
  jobs/metricsgateway/templates/bpm.yml.erb
  jobs/metricsserver/templates/bpm.yml.erb
  jobs/operator/templates/bpm.yml.erb
  jobs/scalingengine/templates/bpm.yml.erb
  jobs/scheduler/templates/bpm.yml.erb
Labels: exclude-from-changelog, allow-acceptance-tests

#2113 Fix path to file in prometheus-release;
  ci/infrastructure/scripts/deploy-prometheus.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#2129 Update golang version to 1.20.5
  .final_builds/packages/golang-1-linux/index.yml
  .tool-versions
  packages/golang-1-linux/spec.lock
  packages/golang-1-linux/vendored-commit
  packages/golang-1-linux/version
Labels: dependencies

#2132 Make prometheus locally deployable;
  Makefile
  ci/infrastructure/scripts/deploy-prometheus.sh
Labels: allow-acceptance-tests

#2145 Adds workflow that helps the bots with intermediate files.
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/dependency-update.go-mod-tidy_and_make-package-specs.yaml
  .github/workflows/tidy-go-mod.yaml
  Makefile
  flake.nix
  src/acceptance/Makefile
  src/acceptance/assets/app/go_app/Makefile
  src/autoscaler/.gitignore
  src/autoscaler/Makefile
  src/autoscaler/fakes/.gitignore
  src/autoscaler/fakes/fakes.go
  src/autoscaler/generate-fakes.go
  src/changelog/Makefile
  src/changeloglockcleaner/Makefile
Labels: allow-acceptance-tests

#2159 Fix the filters for the affected workflow;
  .github/workflows/dependency-update.go-mod-tidy_and_make-package-specs.yaml
  README.md
  ci/autoscaler/pipeline.yml
  flake.nix
Labels: allow-acceptance-tests

#2182 Fix changelog generation
  .github/workflows/acceptance_tests_reusable.yaml
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/dependency-spec-updates.yaml
  .github/workflows/dependency-update.go-mod-tidy_and_make-package-specs.yaml
  .github/workflows/tidy-go-mod.yaml
  Makefile
  ci/autoscaler/scripts/deploy-autoscaler.sh
  src/acceptance/Makefile
  src/acceptance/assets/app/go_app/Makefile
  src/autoscaler/Makefile
  src/changelog/Makefile
  src/changeloglockcleaner/Makefile
Labels: allow-acceptance-tests
