Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2023-10, with the labels that each got.

#2166 Non 5xx return codes
  flake.lock
  src/autoscaler/Makefile
  src/autoscaler/cf/errors.go
  src/autoscaler/scalingengine/scalingengine_test.go
  src/autoscaler/scalingengine/server/scaling_handler.go
  src/autoscaler/scalingengine/server/scaling_handler_test.go
Labels: allow-acceptance-tests

#2198 Fix `credhub-cli` download path
  ci/dockerfiles/autoscaler-deploy/Dockerfile
  ci/dockerfiles/autoscaler-tools/Dockerfile
Labels: dependencies

#2200 Fix make-target “deploy-cleanup”
  .github/workflows/acceptance_tests_broker_close.yaml
  .github/workflows/acceptance_tests_buildin.yaml
  .github/workflows/acceptance_tests_buildin_close.yaml
  .github/workflows/acceptance_tests_reusable.yaml
  ci/autoscaler/scripts/cleanup-autoscaler.sh
Labels: allow-acceptance-tests

#2236 manually update some package for which renovate is failing
  packages/eventgenerator/spec
  src/autoscaler/eventgenerator/client/log_cache_client.go
  src/autoscaler/eventgenerator/client/log_cache_client_test.go
  src/autoscaler/eventgenerator/client/metric_client_factory_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_test.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
Labels: dependencies

#2226 Add ops files to configure upper CPU threshold
  .github/workflows/acceptance_tests_reusable.yaml
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/scripts/run-acceptance-tests.sh
  ci/autoscaler/scripts/vars.source.sh
  operations/cpu_upper_threshold_200.yml
  operations/cpu_upper_threshold_400.yml
Labels: enhancement, allow-acceptance-tests
