Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2024-11, with the labels that each got.

#3302 Adding binding_db to external-db.yml ops file
  operations/external-db.yml
Labels: approved, allow-acceptance-tests

#3311 fix(apiserver) Handle NPE for Custom Metrics Strategy
  src/autoscaler/api/broker/broker_test.go
  src/autoscaler/db/sqldb/binding_sqldb.go
  src/autoscaler/db/sqldb/binding_sqldb_test.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
Labels: allow-acceptance-tests

#3312 Fix(database) Add missing binding db connection details for mysql database
  operations/cf-mysql-db.yml
Labels: bug, allow-acceptance-tests

#3304 Fix(Broker): Return the Same Instance Binding Parameters As Given In Binding Process
  src/acceptance/broker/broker_test.go
  src/autoscaler/api/broker/broker.go
  src/autoscaler/api/brokerserver/broker_handler_test.go
  src/autoscaler/models/binding_configs.go
Labels: bug, allow-acceptance-tests

#3321 Add generate-openapi-generated-clients-and-servers as a dependency for the integration target in Makefile
  Makefile
Labels: exclude-from-changelog

#3320 (feat) Add XFCC authenticated scaling engine endpoint
  ci/autoscaler/scripts/deploy-autoscaler.sh
  jobs/scalingengine/spec
  jobs/scalingengine/templates/scalingengine.yml.erb
  operations/use-cf-services.yml
  packages/scalingengine/spec
  spec/jobs/scalingengine/scalingengine_spec.rb
  src/autoscaler/api/brokerserver/broker_server.go
  src/autoscaler/api/brokerserver/broker_server_suite_test.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/api/publicapiserver/public_api_server_test.go
  src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
  src/autoscaler/build-extension-file.sh
  src/autoscaler/generate-fakes.go
  src/autoscaler/helpers/auth/xfcc_auth.go
  src/autoscaler/helpers/auth/xfcc_auth_test.go
  src/autoscaler/helpers/http_server.go
  src/autoscaler/models/api.go
  src/autoscaler/routes/routes.go
  src/autoscaler/routes/routes_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/main.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_test.go
  src/autoscaler/scalingengine/config/config.go
  src/autoscaler/scalingengine/config/config_test.go
  src/autoscaler/scalingengine/config/testdata/valid.yml
  src/autoscaler/scalingengine/server/server.go
  src/autoscaler/scalingengine/server/server_test.go
  src/autoscaler/testhelpers/certs.go
Labels: allow-acceptance-tests
