Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2024-09, with the labels that each got.

#3155 Enable mta acceptance test in github action
  .github/workflows/acceptance_tests_mta.yaml
  .github/workflows/acceptance_tests_mta_close.yaml
  .github/workflows/acceptance_tests_reusable.yaml
  .golangci.yaml
  ci/autoscaler/scripts/common.sh
  ci/autoscaler/scripts/vars.source.sh
  devbox.lock
  operations/use-cf-services.yml
  packages/eventgenerator/spec
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/metricsforwarder/forwarder/syslog_emitter.go
  src/autoscaler/metricsforwarder/forwarder/syslog_emitter_test.go
  src/autoscaler/metricsforwarder/security-group.json
Labels: allow-acceptance-tests

#3169 chore(deps): Bump app-autoscaler-cli-plugin to v4.0.1
  .github/workflows/linters.yaml
  Gemfile.lock
  devbox.lock
  flake.lock
  nix/packages.nix
  spec/jobs/golangapiserver/apiserver_spec.rb
Labels: dependencies

#3178 chore(ci): Disable Cloud Controller v2 API in CI
  ci/infrastructure/pipeline.yml
Labels: chore, allow-acceptance-tests

#3203 chore(`go.work`): Remove `go.work`
  .gitignore
  ci/autoscaler/tasks/update-sdk/update_golang_package.sh
  go.work
Labels: exclude-from-changelog, allow-acceptance-tests

#3216 chore(deps): Remove unintentional usage of `gopkg.in/errgo.v2`
  packages/golangapiserver/spec
  src/autoscaler/api/config/config.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
Labels: dependencies

#3228 fix(apiserver): Check that app is bound on API routes
  src/acceptance/api/api_test.go
  src/acceptance/helpers/helpers.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/routes/routes.go
Labels: bug, allow-acceptance-tests
