Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2024-08, with the labels that each got.

#3122 Remove unnecessary inputs from concourse Golang and Java jobs
  ci/autoscaler/pipeline.yml
  ci/autoscaler/tasks/update-sdk/go_task.yml
  ci/autoscaler/tasks/update-sdk/java_task.yml
Labels: dependencies

#3124 feat(devbox): Only install plugins if needed
  devbox.json
  devbox.lock
Labels: allow-acceptance-tests

#2988 feat(infrastructure): Bring `multiapps-controller` to CF
  ci/Makefile
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/infrastructure/pipeline.yml
  ci/infrastructure/scripts/deploy-multiapps-controller.sh
  ci/infrastructure/scripts/deploy-postgres.sh
  ci/infrastructure/scripts/deploy-prometheus.sh
  ci/infrastructure/scripts/utils.source.sh
  ci/infrastructure/scripts/vars.source.sh
  ci/infrastructure/tasks/deploy-multiapps-controller.yml
  ci/infrastructure/tasks/deploy-postgres.yml
  ci/operations/add-multiapps-databases-to-postgres.yml
  ci/operations/add-trusted-certs.yaml
  ci/operations/set-postgres-disk.yml
Labels: exclude-from-changelog, allow-acceptance-tests

#3126 poc(metricsforwarder): Use multiapps deploy to run metricsforwarder on cf
  Makefile
  ci/autoscaler/scripts/common.sh
  ci/autoscaler/scripts/deploy-apps.sh
  ci/dockerfiles/autoscaler-tools/Dockerfile
  src/autoscaler/.gitignore
  src/autoscaler/Makefile
  src/autoscaler/example.mtaext
  src/autoscaler/metricsforwarder/Makefile
  src/autoscaler/mta.yaml
Labels: allow-acceptance-tests

#3130 Uses deploment name as default cf space
  ci/autoscaler/scripts/vars.source.sh
Labels: allow-acceptance-tests

#3127 chore(scheduler): Remove usage of Java KeyStore (JKS)
  Makefile
  devbox.json
  devbox.lock
  jobs/scheduler/spec
  jobs/scheduler/templates/bpm-pre-start.erb
  jobs/scheduler/templates/install_crt_keystore.sh
  jobs/scheduler/templates/scheduler.yml.erb
  scripts/generate_test_certs.sh
  src/autoscaler/integration/scheduler_application.template.yml
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/RestClientConfig.java
  src/scheduler/src/main/resources/application.yml
Labels: allow-acceptance-tests

#3128 Makefile improvements
  .editorconfig
  Makefile
  ci/autoscaler/scripts/acceptance-tests-config.sh
  ci/autoscaler/scripts/run-acceptance-tests.sh
  devbox.json
  devbox.lock
  nix/packages.nix
  src/acceptance/Makefile
  src/acceptance/bin/test
  src/autoscaler/Makefile
Labels: allow-acceptance-tests

#3129 autoscaler 775/enable postgres ssl
  ci/autoscaler/pipeline.yml
  ci/autoscaler/scripts/common.sh
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/set-pipeline.sh
  devbox.json
  devbox.lock
  operations/disable-postgres-tls-config.yml
  operations/use-cf-services.yml
  src/autoscaler/metricsforwarder/Makefile
Labels: allow-acceptance-tests

#3134 Patch app-isolation
  .golangci.yaml
  Makefile
  ci/autoscaler/tasks/make/make.sh
  devbox.json
  devbox.lock
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/cred_helper/storedprocedure_cred_helper.go
  src/autoscaler/db/db.go
  src/autoscaler/db/helper.go
  src/autoscaler/db/helper_test.go
  src/autoscaler/db/sqldb/appmetric_sqldb.go
  src/autoscaler/db/sqldb/binding_sqldb.go
  src/autoscaler/db/sqldb/lock_sqldb.go
  src/autoscaler/db/sqldb/policy_sqldb.go
  src/autoscaler/db/sqldb/scalingengine_sqldb.go
  src/autoscaler/db/sqldb/scheduler_sqldb.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb.go
  src/autoscaler/db/sqldb/storedprocedure_sqldb_test.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_suite_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_suite_test.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
  src/autoscaler/sync/sync_suite_test.go
  src/changeloglockcleaner/sqldb/changelogdb.go
  src/changeloglockcleaner/sqldb/helper.go
  src/changeloglockcleaner/sqldb/helper_test.go
  src/changeloglockcleaner/sqldb/sqldb_suite_test.go
Labels: allow-acceptance-tests

#3137 Sets postgres port to current pr number if open pr exists
  ci/autoscaler/pipeline.yml
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/set-pipeline.sh
  operations/use-cf-services.yml
  src/autoscaler/metricsforwarder/Makefile
Labels: exclude-from-changelog, allow-acceptance-tests

#3133 POC(metricsforwarder): Perform a cleanup of mtar deployment and created space
  ci/autoscaler/scripts/cleanup-autoscaler.sh
  ci/autoscaler/scripts/common.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#3139 fix(metricsforwarder): Clear allowed metrics cache once policy is removed.
  src/autoscaler/metricsforwarder/manager/policyManager.go
  src/autoscaler/metricsforwarder/manager/policyManager_test.go
Labels: bug, allow-acceptance-tests

#3140 (fix) autoscaler 775/cleanup mtar
  ci/autoscaler/scripts/cleanup-autoscaler.sh
  ci/autoscaler/scripts/common.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#3141 Adds missing pr variable to set-pipeline job
  ci/autoscaler/pipeline.yml
Labels: exclude-from-changelog, allow-acceptance-tests

#3145 fix(test): Fix `scalingengine_sqldb_test.go`
  src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
Labels: exclude-from-changelog, allow-acceptance-tests

#3125 poc(metricsforwarder): read configuration from environment instead of filesystem
  Makefile
  ci/autoscaler/scripts/deploy-apps.sh
  ci/dockerfiles/autoscaler-tools/Dockerfile
  ci/infrastructure/scripts/deploy-multiapps-controller.sh
  devbox.json
  devbox.lock
  operations/use-cf-services.yml
  packages/metricsforwarder/spec
  src/acceptance/assets/app/go_app/Makefile
  src/autoscaler/Makefile
  src/autoscaler/build-extension-file.sh
  src/autoscaler/configutil/cf.go
  src/autoscaler/configutil/configutil_suite_test.go
  src/autoscaler/configutil/configutil_test.go
  src/autoscaler/example.mtaext
  src/autoscaler/generate-fakes.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/metricsforwarder/.gitignore
  src/autoscaler/metricsforwarder/Makefile
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/metricsforwarder/default_config.json
  src/autoscaler/mta.yaml
Labels: allow-acceptance-tests

#3150 go buildpack
  Makefile
  ci/autoscaler/scripts/deploy-apps.sh
  ci/dockerfiles/autoscaler-tools/Dockerfile
  ci/infrastructure/scripts/deploy-multiapps-controller.sh
  devbox.json
  devbox.lock
  operations/use-cf-services.yml
  packages/metricsforwarder/spec
  src/acceptance/assets/app/go_app/Makefile
  src/autoscaler/Makefile
  src/autoscaler/build-extension-file.sh
  src/autoscaler/configutil/cf.go
  src/autoscaler/configutil/configutil_suite_test.go
  src/autoscaler/configutil/configutil_test.go
  src/autoscaler/example.mtaext
  src/autoscaler/generate-fakes.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/metricsforwarder/.gitignore
  src/autoscaler/metricsforwarder/Makefile
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/metricsforwarder/default_config.json
  src/autoscaler/mta.yaml
Labels: allow-acceptance-tests

#3153 Remove PR_NUMBER check from build-extension-file.sh in autoscaler module
  src/autoscaler/build-extension-file.sh
Labels: allow-acceptance-tests

#3154 feature(metricsforwarder): Enable go buildpack for mtar deployment
  src/autoscaler/.cfignore
  src/autoscaler/Makefile
  src/autoscaler/mta.yaml
Labels: allow-acceptance-tests
