Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2024-06, with the labels that each got.

#2962 test(acceptance): add missing tests for `breach_duration_secs` and `cool_down_secs`
  src/acceptance/app/lead_times_test.go
  src/acceptance/helpers/helpers.go
Labels: enhancement, allow-acceptance-tests

#2977 feat(devbox): Add Cloud MTA Build Tool to devbox
  devbox.json
  local-flake/flake.nix
  scripts/asdf2devbox.py
Labels: dependencies

#2967 poc(metricsforwarder): Deploy metricsforwarder as a cf app
  Makefile
  ci/Makefile
  ci/README.md
  ci/autoscaler/pipeline.yml
  ci/autoscaler/scripts/common.sh
  ci/autoscaler/scripts/deploy-apps.sh
  ci/autoscaler/scripts/deploy-autoscaler.sh
  ci/autoscaler/scripts/vars.source.sh
  ci/autoscaler/set-pipeline.sh
  ci/autoscaler/tasks/deploy-apps.yml
  ci/autoscaler/tasks/update-sdk/update_java_package.sh
  ci/autoscaler/tasks/update-sdk/vendor_package.sh
  ci/scripts/delete-pipeline.sh
  operations/disable-postgres-tls-config.yml
  operations/use-cf-services.yml
  src/acceptance/assets/app/go_app/internal/app/app.go
  src/acceptance/assets/app/go_app/internal/app/custom_metrics.go
  src/autoscaler/Makefile
  src/autoscaler/healthendpoint/server.go
  src/autoscaler/metricsforwarder/.gitignore
  src/autoscaler/metricsforwarder/Makefile
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/metricsforwarder_test.go
  src/autoscaler/metricsforwarder/config/config.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/metricsforwarder/security-group.json
  src/autoscaler/metricsforwarder/server/server.go
  src/autoscaler/metricsforwarder/server/server_suite_test.go
  src/autoscaler/metricsforwarder/server/server_test.go
  templates/app-autoscaler.yml
Labels: allow-acceptance-tests, skip-cleanup

#3031 fix(ci): fix `fly` param value assignment so that `make delete-pipeline` works
  ci/scripts/delete-pipeline.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#3032 fix(readme): drop HTML-tags to fix rendering
  README.md
Labels: bug, exclude-from-changelog, allow-acceptance-tests

#3033 Adds missing variable to deploy-autoscaler script
  ci/autoscaler/scripts/deploy-autoscaler.sh
Labels: allow-acceptance-tests

#3034 fix(ci): make `acceptance-log-cache-syslog` run with a `metricsforwarder` sending metrics to the `loggr-syslog-agent`
  ci/autoscaler/pipeline.yml
Labels: bug, exclude-from-changelog, allow-acceptance-tests

#3035 fix(metrics-architecture): remove configuration referencing the dead table `appinstancemetrics`
  jobs/operator/spec
  operations/connect_to_postgres_with_certs.yml
  operations/disable-postgres-tls-config.yml
  templates/app-autoscaler.yml
Labels: bug, allow-acceptance-tests

#2990 Fix flake
  .editorconfig
  .gitignore
  devbox.json
  flake.lock
  flake.nix
  local-flake/flake.lock
  local-flake/flake.nix
  nix/packages.nix
  nix/packages/uaac/Gemfile
  nix/packages/uaac/Gemfile.lock
  nix/packages/uaac/default.nix
  nix/packages/uaac/gemset.nix
  result
Labels: allow-acceptance-tests

#3046 fix(tests): restore `metricsforwarder` template test
  spec/jobs/golangapiserver/apiserver_spec.rb
  spec/jobs/metricsforwarder/metricsforwarder_spec.rb
  spec/jobs/operator/operator_spec.rb
  spec/jobs/scalingengine/scalingengine_spec.rb
  spec/jobs/scheduler/scheduler_spec.rb
Labels: bug, exclude-from-changelog, allow-acceptance-tests

#3050 Add missing tools;
  devbox.json
  devbox.lock
  flake.nix
Labels: allow-acceptance-tests
