Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2024-12, with the labels that each got.

#3392 chore(devbox): Introduce special nix flake for devbox
  devbox.json
  nix/flake.lock
  nix/flake.nix
Labels: exclude-from-changelog

#3405 Use Correct Type Upon Binding Retrieval
  src/autoscaler/api/broker/broker_test.go
  src/autoscaler/models/binding_configs.go
  src/autoscaler/models/binding_configs_test.go
Labels: allow-acceptance-tests

#3435 chore(renovate): Disable OpenTelementry SDK updates
  .github/workflows/renovate_config_validation.yaml
  renovate.json
Labels: chore

#3434 Change Shebang To Read From Path Variable
  src/acceptance/assets/app/go_app/deploy.sh
  src/acceptance/bin/test_default
  src/acceptance/cleanup.sh
Labels: enhancement, allow-acceptance-tests

#3357 feat(eventgenerator): Integrate cf api with event generator
  src/autoscaler/Makefile
  src/autoscaler/api/cmd/api/api_suite_test.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/api/publicapiserver/middleware.go
  src/autoscaler/api/publicapiserver/middleware_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/api/publicapiserver/public_api_handler_test.go
  src/autoscaler/api/publicapiserver/public_api_server.go
  src/autoscaler/api/publicapiserver/publicapiserver_suite_test.go
  src/autoscaler/build-extension-file.sh
  src/autoscaler/configutil/cf.go
  src/autoscaler/configutil/file.go
  src/autoscaler/eventgenerator/generator/evaluator.go
  src/autoscaler/eventgenerator/generator/evaluator_test.go
  src/autoscaler/helpers/auth/xfcc_auth.go
  src/autoscaler/helpers/auth/xfcc_auth_test.go
  src/autoscaler/helpers/handlers/handlers.go
  src/autoscaler/helpers/httpclient.go
  src/autoscaler/helpers/httpclient_test.go
  src/autoscaler/integration/components_test.go
  src/autoscaler/integration/helpers_test.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_logcache_eventgenerator_scalingengine_test.go
  src/autoscaler/integration/integration_operator_others_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/routes/routes.go
  src/autoscaler/routes/routes_test.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_test.go
  src/autoscaler/scalingengine/server/server_test.go
  src/autoscaler/testhelpers/certs.go
Labels: enhancement
