Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2024-07, with the labels that each got.

#3061 chore(template): Remove unused `metric_scraper_ca`
  templates/app-autoscaler.yml
Labels: chore, allow-acceptance-tests

#3078 chore(deps): replace `nu7hatch/gouuid` with `google/uuid`
  .github/workflows/bosh-release-checks.yaml
  .github/workflows/dependency-updates-post-processing.yaml
  packages/eventgenerator/spec
  packages/golangapiserver/spec
  packages/metricsforwarder/spec
  packages/operator/spec
  packages/scalingengine/spec
  src/autoscaler/api/broker/broker.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/cred_helper/custom_metrics_cred_helper.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
  src/autoscaler/helpers/uuid.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_operator_others_test.go
  src/autoscaler/integration/integration_scheduler_scalingengine_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/operator/cmd/operator/main.go
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_suite_test.go
Labels: dependencies, Do Not Merge, allow-acceptance-tests

#3087 chore(deps) Update java version to 21.0.3
  .gitignore
  Makefile
  ci/autoscaler/pipeline.yml
  ci/autoscaler/tasks/update-sdk/create_pr.sh
  ci/autoscaler/tasks/update-sdk/download_java.sh
  ci/autoscaler/tasks/update-sdk/update_java_package.sh
  ci/autoscaler/tasks/update-sdk/update_package.sh
  ci/autoscaler/tasks/update-sdk/vars.source.sh
  ci/dockerfiles/autoscaler-tools/Dockerfile
  config/blobs.yml
  jobs/eventgenerator/spec
  jobs/eventgenerator/templates/bpm-pre-start.erb
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/bpm-pre-start.erb
  jobs/operator/spec
  jobs/operator/templates/bpm-pre-start.erb
  jobs/scalingengine/spec
  jobs/scalingengine/templates/bpm-pre-start.erb
  jobs/scheduler/spec
  jobs/scheduler/templates/bpm-pre-start.erb
  jobs/scheduler/templates/bpm.yml.erb
  jobs/scheduler/templates/install_crt_truststore.sh
  packages/db/spec
  packages/openjdk-17/spec.lock
  packages/openjdk-17/version
  packages/openjdk-21/packaging
  packages/openjdk-21/spec
  packages/openjdk-21/vendored-commit
  packages/openjdk-21/version
  packages/scheduler/spec
  scripts/update_vendor_packages
  src/common/init-db-truststore.sh
Labels: dependencies

#3102 chore(deps) Bump Google Java Formatter to 1.22.0
  .github/workflows/java-ci-lint.yaml
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManager.java
  style-guide/google-format-ci-v0.1.sh
Labels: dependencies

#3105 chore(dependencies): replace `"dario.cat/mergo` with a custom implementation
  packages/eventgenerator/spec
  src/autoscaler/envelopeprocessor/envelope_processor.go
  src/autoscaler/envelopeprocessor/envelopeprocessor_test.go
  src/autoscaler/eventgenerator/metric/fetcher.go
  src/autoscaler/eventgenerator/metric/fetcher_test.go
  src/autoscaler/go.mod
  src/autoscaler/go.sum
Labels: dependencies, allow-acceptance-tests

#3099 chor(deps) Automate Java Package Version Update
  ci/autoscaler/pipeline.yml
  ci/autoscaler/tasks/update-sdk/download_java.sh
  ci/autoscaler/tasks/update-sdk/update_java_package.sh
  ci/autoscaler/tasks/update-sdk/update_package.sh
Labels: chore, allow-acceptance-tests

#3110 chore(deps): remove unused dependency `github.com/pkg/errors`
  src/autoscaler/go.mod
  src/autoscaler/healthendpoint/health_readiness_test.go
Labels: dependencies, allow-acceptance-tests
