Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2024-03, with the labels that each got.

#2690 Improve test-app deployment
  Makefile
  src/acceptance/assets/app/go_app/deploy.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#2703 Add PostgreSQL version 16 to test matrix
  .github/workflows/postgres.yaml
Labels: exclude-from-changelog

#2724 Switch to `renovate` `best-practices` preset
  renovate.json
Labels: dependencies, exclude-from-changelog

#2729 Improve test-app deployment script
  src/acceptance/assets/app/go_app/deploy.sh
Labels: exclude-from-changelog, allow-acceptance-tests

#2754 fix(deps): `google-cloud-cli` download in `app-autoscaler-release-tools`
  ci/dockerfiles/autoscaler-tools/Dockerfile
Labels: dependencies

#2756 chore(images): Remove `-test` and `-deploy` images
  .github/workflows/image.yaml
  ci/autoscaler/tasks/check-diego-cell-count.yml
  ci/autoscaler/tasks/cleanup-autoscaler.yml
  ci/autoscaler/tasks/deploy-previous-autoscaler.yml
  ci/autoscaler/tasks/register-broker.yml
  ci/autoscaler/tasks/release-autoscaler.yml
  ci/autoscaler/tasks/update-sdk/task.yml
  ci/dockerfiles/autoscaler-deploy/Dockerfile
  ci/dockerfiles/autoscaler-test/Dockerfile
  ci/infrastructure/tasks/check-for-existing-deployments.yml
  ci/infrastructure/tasks/combine-ops.yml
  ci/infrastructure/tasks/deploy-prometheus.yml
Labels: exclude-from-changelog

#2757 Bump to exact Go versions during `update-golang`
  ci/autoscaler/tasks/update-sdk/update_golang_package.sh
  ci/terragrunt/app-autoscaler/concourse/pipelines/api-tester/src/go.mod
  go.work
  src/acceptance/assets/app/go_app/go.mod
  src/acceptance/go.mod
  src/autoscaler/Makefile
  src/autoscaler/go.mod
  src/changelog/go.mod
  src/changeloglockcleaner/go.mod
Labels: exclude-from-changelog, allow-acceptance-tests

#2801 chore(deps): Bundle `ginkgo` updates
  .github/dependabot.yaml
  renovate.json
Labels: dependencies

#2790 feat(cpuutil): Add new metric type `cpuutil`
  api/shared_definitions.yaml
  ci/infrastructure/pipeline.yml
  ci/operations/set-cpu-entitlement-per-share.yaml
  flake.nix
  jobs/golangapiserver/spec
  jobs/golangapiserver/templates/apiserver.yml.erb
  src/acceptance/Makefile
  src/acceptance/README.md
  src/acceptance/api/api_suite_test.go
  src/acceptance/app/app_suite_test.go
  src/acceptance/app/dynamic_policy_test.go
  src/acceptance/broker/broker_suite_test.go
  src/acceptance/config/config.go
  src/acceptance/config/config_test.go
  src/acceptance/helpers/apps.go
  src/acceptance/helpers/helpers.go
  src/acceptance/post_upgrade/post_upgrade_suite_test.go
  src/acceptance/pre_upgrade/pre_upgrade_suite_test.go
  src/acceptance/run_performance/run_performance_suite_test.go
  src/acceptance/setup_performance/setup_performance_suite_test.go
  src/autoscaler/api/broker/broker.go
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/api/config/testdata/valid_config.yml
  src/autoscaler/api/policyvalidator/policy_validator.go
  src/autoscaler/api/policyvalidator/policy_validator_test.go
  src/autoscaler/api/publicapiserver/public_api_handler.go
  src/autoscaler/db/sqldb/policy_sqldb_test.go
  src/autoscaler/db/sqldb/scalingengine_sqldb_test.go
  src/autoscaler/db/sqldb/sqldb_suite_test.go
  src/autoscaler/envelopeprocessor/envelope_processor.go
  src/autoscaler/envelopeprocessor/envelopeprocessor_test.go
  src/autoscaler/eventgenerator/aggregator/metric_poller.go
  src/autoscaler/eventgenerator/client/log_cache_client.go
  src/autoscaler/eventgenerator/client/log_cache_client_test.go
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/forwarder/metric_forwarder.go
  src/autoscaler/metricsforwarder/server/auth/authenticator.go
  src/autoscaler/metricsforwarder/server/custom_metrics_handlers.go
  src/autoscaler/metricsserver/collector/envelope_processor_test.go
  src/autoscaler/models/metrics.go
  src/autoscaler/testhelpers/clients.go
Labels: allow-acceptance-tests
