Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2025-01, with the labels that each got.

#3439 Custom-Metrics: Set default_credential_type to x509 (mTLS) - Breaking Change
  jobs/golangapiserver/spec
  spec/jobs/golangapiserver/apiserver_spec.rb
  src/acceptance/app/custom_metric_test.go
  src/acceptance/app/lead_times_test.go
  src/acceptance/helpers/helpers.go
Labels: breaking-change, allow-acceptance-tests

#3444 Check – before creating an index for the app-metrics – if it is already there.
  src/autoscaler/eventgenerator/db/dataaggregator.db.changelog.yml
Labels: chore

#3445 fix(perf.tests) Use mTLS to send custom metrics
  Makefile
  ci/autoscaler/scripts/run-acceptance-tests.sh
  ci/autoscaler/scripts/vars.source.sh
  devbox.json
  devbox.lock
  src/acceptance/app/custom_metric_test.go
  src/acceptance/helpers/apps.go
  src/acceptance/run_performance/run_performance_test.go
Labels: bug, chore, allow-acceptance-tests

#3456 chore(scheduler): Replace deprectated Mockito annotations
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/dao/ActiveScheduleDaoImplFailureTest.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/quartz/AppScalingScheduleJobTest.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleRestControllerTest.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/rest/ScheduleSyncRestControllerTest.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleJobManagerTest.java
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/service/ScheduleManagerTest.java
Labels: chore

#3474 feat: replace `swagger-cli` with `redocly` for OpenAPI validation
  .github/workflows/openapi-specs-check.yaml
  Makefile
  devbox.json
  devbox.lock
  flake.nix
Labels: dependencies
