Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2025-02, with the labels that each got.

#3490 fix(mta): Ensure apps can be staged in air gapped environments
  src/autoscaler/Makefile
  src/autoscaler/mta.tpl.yaml
Labels: bug

#3512 chore(renovate): Also run during office hours
  renovate.json
Labels: exclude-from-changelog

#3437 Add HTTP/XFCCAuth endpoint in the scheduler component
  .gitignore
  Makefile
  devbox.lock
  jobs/scheduler/spec
  jobs/scheduler/templates/scheduler.yml.erb
  packages/eventgenerator/spec
  packages/operator/spec
  packages/scalingengine/spec
  scripts/generate_test_certs.sh
  spec/jobs/scheduler/scheduler_spec.rb
  src/acceptance/api/api_test.go
  src/autoscaler/Makefile
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/cmd/api/main.go
  src/autoscaler/api/config/config.go
  src/autoscaler/api/config/config_test.go
  src/autoscaler/cf/config.go
  src/autoscaler/configutil/cf.go
  src/autoscaler/configutil/configutil_test.go
  src/autoscaler/db/db.go
  src/autoscaler/helpers/auth/xfcc_auth.go
  src/autoscaler/helpers/health.go
  src/autoscaler/helpers/http_server.go
  src/autoscaler/helpers/logger.go
  src/autoscaler/integration/components_test.go
  src/autoscaler/integration/gorouterproxy/Readme.md
  src/autoscaler/integration/gorouterproxy/gorouterproxy_suite_test.go
  src/autoscaler/integration/gorouterproxy/gorouterproxy_test.go
  src/autoscaler/integration/gorouterproxy/main.go
  src/autoscaler/integration/integration_golangapi_eventgenerator_test.go
  src/autoscaler/integration/integration_golangapi_scalingengine_test.go
  src/autoscaler/integration/integration_golangapi_scheduler_test.go
  src/autoscaler/integration/integration_logcache_eventgenerator_scalingengine_test.go
  src/autoscaler/integration/integration_operator_others_test.go
  src/autoscaler/integration/integration_scheduler_scalingengine_test.go
  src/autoscaler/integration/integration_suite_test.go
  src/autoscaler/integration/scheduler_application.template.yml
  src/autoscaler/metricsforwarder/cmd/metricsforwarder/main.go
  src/autoscaler/metricsforwarder/config/config_test.go
  src/autoscaler/models/api.go
  src/autoscaler/models/ratelimit.go
  src/autoscaler/models/security.go
  src/autoscaler/testhelpers/certs.go
  src/autoscaler/testhelpers/cf.go
  src/scheduler/.vscode/launch.json
  src/scheduler/Makefile
  src/scheduler/pom.xml
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/conf/CfHttpConfiguration.java
  src/scheduler/src/main/java/org/cloudfoundry/autoscaler/scheduler/filter/HttpAuthFilter.java
  src/scheduler/src/main/resources/application.yml
  src/scheduler/src/test/java/org/cloudfoundry/autoscaler/scheduler/filter/HttpAuthFilterTest.java
Labels: allow-acceptance-tests
