Repository cloudfoundry/app-autoscaler-release, pull requests merged in 2025-05, with the labels that each got.

#3790 Increase key length to 4096 for Postgres-related SSL
  operations/add-postgres-variables.yml
Labels: enhancement

#3784 Revert set pipeline to working version
  ci/autoscaler/set-pipeline.sh
Labels: exclude-from-changelog

#3801 Increase timeout for concourse app task e.g app, broker api test suites
  ci/autoscaler/pipeline.yml
Labels: chore

#3717 (feature): Enable operator in mtar deployment
  devbox.lock
  jobs/eventgenerator/templates/eventgenerator.yml.erb
  jobs/operator/templates/operator.yml.erb
  operations/configure-cf-services.yml
  operations/use-cf-services.yml
  packages/operator/spec
  spec/jobs/eventgenerator/eventgenerator_spec.rb
  spec/jobs/operator/operator_spec.rb
  src/autoscaler/Makefile
  src/autoscaler/api/cmd/api/api_test.go
  src/autoscaler/api/config/config.go
  src/autoscaler/build-extension-file.sh
  src/autoscaler/configutil/cf.go
  src/autoscaler/configutil/configutil_test.go
  src/autoscaler/db/db.go
  src/autoscaler/eventgenerator/cmd/eventgenerator/eventgenerator_suite_test.go
  src/autoscaler/eventgenerator/config/config_test.go
  src/autoscaler/eventgenerator/default_config.json
  src/autoscaler/integration/components_test.go
  src/autoscaler/mta.tpl.yaml
  src/autoscaler/operator/cmd/operator/main.go
  src/autoscaler/operator/cmd/operator/operator_suite_test.go
  src/autoscaler/operator/cmd/operator/operator_test.go
  src/autoscaler/operator/config/config.go
  src/autoscaler/operator/config/config_test.go
  src/autoscaler/operator/config/testdata/invalid.yml
  src/autoscaler/operator/config/testdata/partial.yml
  src/autoscaler/operator/config/testdata/valid.yml
  src/autoscaler/operator/default_config.json
  src/autoscaler/operator/exampleconfig/example.yml
  src/autoscaler/scalingengine/cmd/scalingengine/scalingengine_test.go
  src/autoscaler/testhelpers/health_endpoint.go
Labels: deploy-to-cf
